### ISSUE TITLE
Separate modules from data

### ISSUE THREAD

**Issue by henrykironde** [weecology/DeepForest#113]
The data is in `DeepForest/deepforest/data/` directory.
I can move that to `DeepForest/data` to have modules separate from data.

**Comment by bw4sz** [comment]
Sounds good. Is there overall logic to why this is better? I'll need to rewrite tests. I want to make sure the deepforest.get_data() function still works. I don't want users to have to know where DeepForest is installed to have to access sample data, but I think using the relative path from the `DeepForest/deepforest/` directory should be fine.

**Comment by ethanwhite** [comment]
Here are a couple of good sources on how to handle data in Python packages:

* https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files
* https://python-packaging.readthedocs.io/en/latest/non-code-files.html

From a quick skim we may want to keep this in the module directory (see below quote from second source):

> Files which are to be used by your installed library (e.g. data files to support a particular computation method) should usually be placed inside of the Python module directory itself. E.g. in our case, a data file might be at funniest/funniest/data.json. That way, code which loads those files can easily specify a relative path from the consuming module’s __file__ variable.

**Comment by henrykironde** [comment]
Will go ahead and close this
