### ISSUE TITLE
Handle licensing for keras-retinanet fork

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#115]
Internal to this repo is a fork of `keras-retinanet` (I'm assuming: https://github.com/fizyr/keras-retinanet). This package has an Apache 2.0 license. DeepForest is MIT. These are both permissive licenses so we should be able to address this, but simply licensing the whole repo as MIT isn't the way to do this. We need to explore how to handle this properly if the `keras-retinanet` fork is going to remain in this repo.

**Comment by ethanwhite** [comment]
I don't think we need consent (and if we did I don't think we'd want to work this way). I think we need to either:

1. Find documentation that re-licensing Apache 2.0 code as MIT is OK (possibly doable with attribution since it's a permissive license)

or

2. Figure out how to properly sub-license a sub-module within a Python package.

**Comment by bw4sz** [comment]
https://opensource.stackexchange.com/questions/7384/proper-way-of-migrating-mit-licensed-code-to-apache-2-0-license suggests we are on the right track.

**Comment by ethanwhite** [comment]
Great, so re-licensing given the modifications is probably OK, but it needs to be documented and the original license and attribution kept, which we haven't done yet. That should all go in the external library's directory. If  the CONTRIBUTORS file from the upstream repo was present when you forked it should be added back to the subdirectory in the state it was in when you worked. We also want a LICENSE file in that directory. It can either stay as Apache 2, but note the original copyright and then that on the modifications, or you can re-license in the way described.

This is another useful source: https://opensource.stackexchange.com/questions/7467/copyright-of-mit-licenced-libraries-usage-within-gpl-licensed-code
