### ISSUE TITLE
problem giving other pictures as imput

### ISSUE THREAD

**Issue by quietNightTime** [weecology/DeepForest#118]
**Describe the bug**
I want to test deepforst to count the amount of trees in a picture. But I can't get the software to "recognize" my picture. I can run the benchmark test but can't use my own picture

**To Reproduce**
I start anaconda and open a "CMD.exe promt", I activate my virtual environment "testdeepf" and then I start python.
I used the following code:
![image](https://user-images.githubusercontent.com/16447853/80760387-1d592680-8b39-11ea-8d48-d086d94d5983.png)

and this is the list of everything installed in the virtual environment.
![image](https://user-images.githubusercontent.com/16447853/80760531-57c2c380-8b39-11ea-9261-df611058dea1.png)

I checked and the picture (test_arb_tree3) is in the library.
![image](https://user-images.githubusercontent.com/16447853/80760702-9eb0b900-8b39-11ea-9641-c396ce266966.png)

it is the following picture (400x400):
![image](https://user-images.githubusercontent.com/16447853/80760890-e8010880-8b39-11ea-800c-3093350a8eaa.png)

and was cropped from this picture:
![test_arb_tree2](https://user-images.githubusercontent.com/16447853/80760953-0109b980-8b3a-11ea-9154-925a98aca962.jpg)

**Expected behavior**
I expected that if the picture was of the TIF format and in the lib that deepforest could use it but it appears to be not that easy.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Crome

PS: I also tried to use the online test service at http://tree.westus.cloudapp.azure.com/shiny/ but I could upload a image but it never processed this was about 10 days ago so it might have been fixed

**Comment by bw4sz** [comment]
Thanks for the report. Your expected behavior is corrected. You don't even need to create a crop. DeepForest predict_tile() method cuts the image into pieces and recombines. Your image looks suitable. Tifs should be fine, there must be something specific about your image. Here is an example

```
from deepforest import deepforest
import matplotlib.pyplot as plt
model = deepforest.deepforest()
model.use_release()
img=model.predict_image("/Users/ben/Documents/NeonTreeEvaluation/evaluation/RGB/JERC_019.tif",return_plot=True)
plt.imshow(img[:,:,::-1])
```

yields
![image](https://user-images.githubusercontent.com/1208492/80764859-72c01400-8af6-11ea-9a20-189cf30ff2ff.png)

Can you share your original .tif? The uploaded files are png.

**Comment by quietNightTime** [comment]
If I try to drag my TIF file into the message I get the following warning.
![image](https://user-images.githubusercontent.com/16447853/80765123-87c29480-8b42-11ea-8fa9-c2c67dfc8b56.png)

The original picture was JPG and I just saved it as a TIF file.

**Comment by bw4sz** [comment]
yeah, you need to share it some other way, this won't let you do tif. Dropbox? Email (ben.weinstein@weecology.org). As an aside, you don't need the get_data(), that's just the package data so people can have data to follow along the examples. That's the 2nd user to do that, i'll make it clearer. You can place your data anywhere you like and supply the full path.

**Comment by quietNightTime** [comment]
I will mail it and will try out the code to test it.

**Comment by bw4sz** [comment]
My sense is that the channel order is different than expected. It sounds like an easy fix to warn users once we figure it out. I got reasonable (can be improved) results with your jpg image

```
model.config["score_threshold"] = 0.01
tile = model.predict_tile("/Users/ben/Desktop/test.jpg",return_plot=True,patch_overlap=0,iou_threshold=0.05)
fig = plt.figure(figsize=(20,20))
plt.imshow(tile)
```

![image](https://user-images.githubusercontent.com/1208492/80766007-3c37c880-8af9-11ea-9c7c-c0aa010f4f38.png)

**Comment by quietNightTime** [comment]
Indeed looks promising, I will use the code tomorrow. Thanks for the quick help.
I might have a few more questions the coming weeks I am working on my postgraduate thesis and it involves a inspection drone to help manage a tree nursery.

**Comment by bw4sz** [comment]
Great. I'll find out what's going on with the .tiff. Can I add the image to FAQ? it makes a decent example.

**Comment by quietNightTime** [comment]
yes you can add them to the FAQ
