### ISSUE TITLE
Add conda install information to docs

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#127]
@henrykironde @ethanwhite once conda is ready, we should add it to install. A couple questions.

1. Should we suggest conda over pip? Under what circumstances should we advice users to use pip if ever?
2. What kind of tests should I add to the azure build pipeline to make sure conda install works? Does conda do its own operating system tests? 
3. I'll need to know a bit more about how to maintain this workflow moving forward. Does it require separating tagging from pypi pip releases? Are they automatically synced?

**Comment by ethanwhite** [comment]
1. I don't think we need to specify a preference. Folks using Python will already use one or the other so just provide install lines for both approaches. The only time to express a preference is if pip installs are difficult due to compiled dependencies, but you've handled that already.

I'll let @henrykironde address 2 & 3.

**Comment by henrykironde** [comment]
These are really very good points of concern.

> Should we suggest Conda over pip? Under what circumstances should we advice users to use pip if ever?

We should inform people of Conda first, but we should also include pypi instructions. Our goals is to cover all avenues but Conda would have precedence 

> What kind of tests should I add to the azure build pipeline to make sure conda install works? Does conda do its own operating system tests?

Currently we are testing on Conda linux, we can add win by removing the tag skip: True [win].
This may need some more effort to get to working.

> I'll need to know a bit more about how to maintain this workflow moving forward. Does it require separating tagging from pypi pip releases? Are they automatically synced?

So locally we have are testing just the source code. 
https://github.com/weecology/DeepForest/blob/master/conda_recipe/meta.yaml
This file will need to be updated in the after a pypi release where we update the source section from

```
{% set name = "deepforest" %}
{% set version = "0.2.15" %}
{% set sha256 = "8860ce455f3a03704f80f8efbdbbd240e2bdd10446c7ddd1cd8acc5b3b1bc189" %}
{% set python_version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
```

to

```
  
{% set name = "DeepForest" %}
{% set version = "0.2.15" %}  # new version and new sha
{% set sha256 = "8860ce455f3a03704f80f8efbdbbd240e2bdd10446c7ddd1cd8acc5b3b1bc189" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
```
