### ISSUE TITLE
Unclear on how to install/use GPU for this

### ISSUE THREAD

**Issue by mjb-oz** [weecology/DeepForest#147]
Hi there,

Thanks for open sourcing this project, it's a super cool tool you've built, I'm having lots of fun playing with it.

I'm having a go at running DeepForest over a big area and was hoping to use a Google Cloud based VM with GPU attached for this purpose.
However, the version of TensorFlow that DeepForest uses (v1.14) seems to be quite old and isn't supported by GC anymore, so I can't use any of their off-the-shelf deeplearning VM images (which come with CUDA and cuDNN installed and working).
I've tried to make my own VM to the same effect, but when I install Deepforest, it uses tensorflow=1.14 not tensorflow-gpu=1.14 (which is likely what is missing based on https://www.tensorflow.org/install/gpu).

I'm curious as to if anyone has any experience/recommendations for getting DeepForest working with GPU.
My thoughts are either:
- using a more recent version of TF (does that still work with DeepForest, or are there non-backwards compatible API changes or similar that break DeepForest?),or;
- changing the environment.yml to tensorflow-gpu and then installing from a local version of the repo.
Has anyone tried these and had success?

Any other thoughts/tips/warnings in general about DeepForest with GPU?

Thanks!
- Mike

**Comment by bw4sz** [comment]
Hey Mike I didn't see this until today.  There is no issue using deepforest on GPU, we do it daily. Any machine that installs tensorflow 1.14.0 will detect it like normal. Yes, there is a more recent tf version, but there are many thousand open source projects using pre 2.0 code. We will update it sometime next year, its a bit of a chore. Just install in a conda env and pin the tensorflow version.

I just did 
```
conda create --name test python=3.7
conda activate test
pip install DeepForest
pip install tensorflow-gpu==1.14.0
```
and you should be good to go. Drop some code in here if you need help.
