### ISSUE TITLE
AttributeError: 'deepforest' object has no attribute 'prediction_model'

### ISSUE THREAD

**Issue by L-u-d-0-v-i-c** [weecology/DeepForest#151]
Hello,

I'm trying to simply predict an image (but I have the same error with predict_tile) and I get the following error:

`Traceback (most recent call last):
  File "C:/Users/lleg/PycharmProjects/DeepForest/DeepForest.py", line 9, in <module>
    predicted_raster = test_model.predict_image(image_path=raster_path, show=False, return_plot = False)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\deepforest.py", line 359, in predict_image
    if (self.prediction_model is None):
AttributeError: 'deepforest' object has no attribute 'prediction_model`

Any idea?

Thanks,

Ludovic

**Comment by bw4sz** [comment]
Can I see a full set of code, hard to guess at. I am guessing you did load or train any model. 

```
from deepforest import deepforest
import matplotlib.pyplot as plt
model = deepforest.deepforest()
model.use_release()
img=model.predict_image("/Users/ben/Documents/NeonTreeEvaluation/evaluation/RGB/JERC_019.tif",return_plot=True)

#predict_image returns plot in BlueGreenRed (opencv style), but matplotlib likes RedGreenBlue, switch the channel order.
plt.imshow(img[:,:,::-1])
```

**Comment by L-u-d-0-v-i-c** [comment]
Actually, when I use the code on deepforest.readthedocs.io to predict the provided test images I got the same error:

```
from deepforest import deepforest
from deepforest import get_data

test_model = deepforest.deepforest()
test_model.use_release()

# Find the tutorial data using the get data function.
# For non-tutorial images, you do not need the get_data function,
# provide the full path to the data anywhere on your computer.

raster_path = get_data("OSBS_029.tif")
# Window size of 300px with an overlap of 25% among windows for this small tile.
predicted_raster = test_model.predict_tile(raster_path, return_plot = True, patch_size=300,patch_overlap=0.25)
```
Error:
```
Traceback (most recent call last):
  File "C:/Users/lleg/PycharmProjects/DeepForest/DeepForest.py", line 23, in <module>
    predicted_raster = test_model.predict_tile(raster_path, return_plot = True, patch_size=300,patch_overlap=0.25)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\deepforest.py", line 442, in predict_tile
    score_threshold=self.config["score_threshold"])
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\deepforest.py", line 359, in predict_image
    if (self.prediction_model is None):
AttributeError: 'deepforest' object has no attribute 'prediction_model'
```

**Comment by bw4sz** [comment]
Very interesting, I've never seen that before. This would suggest the release model is not actually being downloaded. I can see you are inside of an Anaconda environment, did you pip or conda install?

The prediction model is created on use_release()
https://github.com/weecology/DeepForest/blob/58bd85de2d180dc27ba2f3fee369ea16161bcb34/deepforest/deepforest.py#L178

I'm looking now to see how we can debug this.

**Comment by L-u-d-0-v-i-c** [comment]
Actually, with the use_release() function I have an error, but I thought it was because the model had already been downloaded. Here's what I get:

```
C:\Users\lleg\Anaconda3\envs\test\python.exe C:/Users/lleg/PycharmProjects/DeepForest/DeepForest.py
Using TensorFlow backend.
Reading config file: C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\data\deepforest_config.yml
A blank deepforest object created. To perform prediction, either train or load an existing model.
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/v0.3.0 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/v0.3.0
Traceback (most recent call last):
  File "C:/Users/lleg/PycharmProjects/DeepForest/DeepForest.py", line 15, in <module>
    test_model.use_release()
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\deepforest.py", line 170, in use_release
    self.model = utilities.read_model(self.weights, self.config)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\utilities.py", line 49, in read_model
    model = models.load_model(model_path, backbone_name='resnet50')
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\deepforest\keras_retinanet\models\__init__.py", line 83, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\lleg\Anaconda3\envs\test\lib\site-packages\keras\engine\saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

Thanks for your help!

**Comment by bw4sz** [comment]
Nope thats the real error. That feels like a python versioning issue. Python version? It shouldn't have let you install on python 3.8 or 2.*

**Comment by L-u-d-0-v-i-c** [comment]
I have a 3.7 version. Deepforest installed with the following command:

```
conda create --name test python=3.7
conda activate test
conda install -c conda-forge deepforest
```

**Comment by bw4sz** [comment]
I just did it from without a problem, let me try conda. I'm sure this is very recent and very small. Thanks for reporting.

**Comment by bw4sz** [comment]
Yup, this is upstream (and nasty huge) of DeepForest. The new version of h5py breaks keras. Well known and being fixed. I'll update all the pins. 

[](https://github.com/h5py/h5py/issues/1732)

For the moment you should easily be able to do. 

```
conda install h5py==2.10.0
```
Please confirm and close when ready.

**Comment by bw4sz** [comment]
Pushed tag 0.33 that pins, should be up on pypi in about an hour, doing conda feedstock now.

**Comment by L-u-d-0-v-i-c** [comment]
> Yup, this is upstream (and nasty huge) of DeepForest. The new version of h5py breaks keras. Well known and being fixed. I'll update all the pins.
> 
> [here](https://github.com/h5py/h5py/issues/1732)
> 
> For the moment you should easily be able to do.
> 
> ```
> conda install h5py==2.10.0
> ```
> 
> Please confirm and close when ready.

It worked. Thanks!

**Comment by AakhashSekar** [comment]
Hi I am still getting this issue 
    model = deepforest.deepforest()
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'deepforest' has no attribute 'deepforest'

not sure how to fix it. could anyone help me on it ASAP

**Comment by ethanwhite** [comment]
This is a really outdated command. What version of deepforest are you using? The current version of this:

```python
from deepforest import main
model = main.deepforest()
model.use_release()
```

I'd recommend updating to the current version (based on Pytorch) and following the [Getting Started](https://deepforest.readthedocs.io/en/latest/getting_started.html) guide

**Comment by AakhashSekar** [comment]
It worked thank you :_)

**Comment by ethanwhite** [comment]
Great! Glad it helped!
