### ISSUE TITLE
I have a question in "Comet visualization" section :) 

### ISSUE THREAD

**Issue by landkwon94** [weecology/DeepForest#156]
First of all, thank you for your nice and beautiful code.

In DeepForest documentation homepage, https://deepforest.readthedocs.io/en/latest/training.html

There is a  section of "Comet visualization".

You wrote : 

from comet_ml import Experiment
comet_experiment = Experiment(api_key=<api_key>,
                                  project_name=<project>, workspace=<"username">)

comet_experiment.log_parameters(**_deepforest_model_**.config)

test_model.train(annotations=annotations_file, input_type="fit_generator",comet_experiment=comet_experiment)

![image](https://user-images.githubusercontent.com/73383617/104303180-1af2fd00-550d-11eb-8b54-f9ae5ee5cfe5.png)

So, I just followed your source code. But, there is not " _deepforest_model_ " in anywhere. What does this variable_name mean?

In your documentation, you didn't use this name anywhere, so I cannot guess what it means....

And I thought that this mean "test_model" in your code, so I modified to it. 

However, as you see the picture below,, it doesn't seam "test_model", because the graph looks so weird. (It is really different from your photo in documentation)

1) This is your photo.
![image](https://user-images.githubusercontent.com/73383617/104303337-51c91300-550d-11eb-8993-69dacecbbb8c.png)

2) However, this is mine(comet_ML)
![image](https://user-images.githubusercontent.com/73383617/104304456-bcc71980-550e-11eb-8277-685d9076190a.png)
![image](https://user-images.githubusercontent.com/73383617/104304490-c5b7eb00-550e-11eb-85f1-b36c59963c09.png)
![image](https://user-images.githubusercontent.com/73383617/104304512-cc466280-550e-11eb-8696-68e036890680.png)

I want to know what " _deepforest_model_ " in your code actually mean. May I ask this question? 
(If possible, also I want to know how to make a plot on vscode(or pychram etc.) not on cometML.. It always make an error whenever I tried to revise the code to generate plot on my code tool(vscode)... please look my photo below.... )

My entire code is : 

from comet_ml import Experiment

import os
from deepforest import get_data
from deepforest import deepforest
from deepforest import utilities
from deepforest import preprocess

YELL_xml = get_data("2019_YELL_2_528000_4978000_image_crop2.xml")
annotation = utilities.xml_to_annotations(YELL_xml)
annotation.head()

annotation.to_csv("train_example.csv", index=False)

YELL_train = get_data("2019_YELL_2_528000_4978000_image_crop2.tiff")
crop_dir = os.getcwd()
train_annotations= preprocess.split_raster(path_to_raster=YELL_train,
                                 annotations_file="train_example.csv",
                                 base_dir=crop_dir,
                                 patch_size=400,
                                 patch_overlap=0.05)

train_annotations.head()

annotations_file= os.path.join(crop_dir, "train_example.csv")
train_annotations.to_csv(annotations_file,index=False, header=None)

test_model = deepforest.deepforest()
test_model.use_release()

test_model.config["epochs"] = 1
test_model.config["save-snapshot"] = False
test_model.train(annotations=annotations_file, input_type="fit_generator")

mAP = test_model.evaluate_generator(annotations=annotations_file)
print("Mean Average Precision is: {:.3f}".format(mAP))

test_model.plot_curves()

and this is the plot result.
![image](https://user-images.githubusercontent.com/73383617/104307892-2812ea80-5513-11eb-966c-64cd9594a637.png)

Is there something I have to do more?

Also, thank you for your nice code :) 

- Sincerely, landkwon -

**Comment by bw4sz** [comment]
You were right that this could have been better illustrated. test_model was the right connection, its just the name of model instance. I can try to get some time look at the code. Just quick glance, you ran for only 1 epoch 
```
test_model.config["epochs"] = 1
```

So there is no points on the graph to connect. Run for longer? Epochs are a full run through the dataset, depending on the problem you will atleast a few dozen (https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/).

**Comment by landkwon94** [comment]
Thank you so much for your comments. I really appreciate it, and again, thank you for nice code! :)
