### ISSUE TITLE
AttributeError: module 'deepforest' has no attribute 'deepforest'

### ISSUE THREAD

**Issue by ahjavid** [weecology/DeepForest#188]
**Describe the bug**
I am trying to replicate the getting started example for DeeForest on Google Colab, but I get error for not finding the deepforest attribute!

**To Reproduce**
!pip install deepforest
from deepforest import deepforest
import matplotlib.pyplot as plt
model = deepforest.deepforest()
model.use_release()
img=model.predict_image("/Users/ben/Documents/NeonTreeEvaluation/evaluation/RGB/JERC_019.tif",return_plot=True)

#predict_image returns plot in BlueGreenRed (opencv style), but matplotlib likes RedGreenBlue, switch the channel order.
plt.imshow(img[:,:,::-1]

Please post any code, no matter how long and its full output. Its much more useful that descriptions.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47865545/116719559-d21e6180-a9a0-11eb-85c5-ddcace2b39f6.png)

**Desktop (please complete the following information):**
 - OS: GoogleColab
 - Browser Chrome
 - Version 90

**Comment by malayjoshi13** [comment]
Hi @ahjavid, instead of using ````!pip install deepforest```, please use ``!pip install DeepForest```. Once you install it then go on importing modules in same way as you are doing right now. It is self verified as I am also working with DeepForest library in Google Colab. Please let me know if you still face any issue.

**Comment by ahjavid** [comment]
> Hi @ahjavid, instead of using `!pip install deepforest`, please use `!pip install DeepForest`. Once you install it then go on importing modules in same way as you are doing right now. It is self verified as I am also working with DeepForest library in Google Colab. Please let me know if you still face any issue.

Hi @malayjoshi13, Thank you for your help.
I tried again but your solution does no seem to work either.
Surprisingly whether I choose to install using "!pip install DeepForest" or "!pip install deepforest", the error still persistent in the next step of runining the example.
Please see the attached screenshot:
![image](https://user-images.githubusercontent.com/47865545/117178666-e8109580-ad97-11eb-805b-e6f48b1f9703.png)

**Comment by malayjoshi13** [comment]
@ahjavid you are on right path. Just follow second approach and in addition to what you are doing right now just add one step extra of reinstalling numpy module. Refer to video below (please ignore screen flickering):

https://user-images.githubusercontent.com/71775151/117186581-9cda9f00-adf8-11eb-8edc-9dcfab544f24.mp4

The code for above video: https://colab.research.google.com/drive/1JsGYw-_45N1Xv0UuDs2ir3RL1UIJ9fNv?usp=sharing 

So the main thing is to run code snippet for re-installing numpy and as and when prompted restarting runtime. Please tell if you still face any issue.

**Comment by malayjoshi13** [comment]
Also you can leave mounting google drive code. I did it because my test image was in my google drive.

**Comment by ahjavid** [comment]
Thank you so much @malayjoshi13! Your solution worked perfectly.

**Comment by malayjoshi13** [comment]
That's great :)
