### ISSUE TITLE
Upload 2015 orthos from T into Hypergator

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#2]
@MarconiS

I'm still trying understand overlap among the different ground truth/year layers. 

put it here?

/orange/ewhite/NeonData/2015_Campaign/D03/OSBS/L1

**Comment by MarconiS** [comment]
Data are update in /orange/ewhite/NeonData/2015_Campaign/D03/OSBS/L3/Orthophoto. The reason why it is L3 is because I'm uploading the 1km2 tiled data (and not the entire flightpaths), consistently with NEON data hierarchy structure

**Comment by bw4sz** [comment]
👍
