### ISSUE TITLE
I have some problem..

### ISSUE THREAD

**Issue by spermking93** [weecology/DeepForest#200]
hello. i'm korean college student 

i use PyCharm ide and i want use deepforest

so, i run terminal and write "pip install deepforest" 

after installation, i verify the version of deepforest is 0.3.8 ..  

So the docs are useless.

What's the problem?

**Comment by ethanwhite** [comment]
Hi @spermking93  - we're glad that you're interested in `deepforest`, but showing up in the issue queue and saying "So the docs are useless. What's the problem?" is not an appropriate way to engage as part of our community, so I'm going to close this issue.

If you are having trouble using the package and are willing to engage with folks here in a positive manner you are welcome to open a new issue. A useful issue typically starts with an informative title and then describes the problem you are having, the code you ran, what happened when you ran that code, and how that differed from what you were expecting.

**Comment by spermking93** [comment]
Sorry. for my rudeness
My intention was mistaken by my English ability
My original intention was 'not working', not 'useless'.
From now on, i will do my best to deliver it more politely.
Sorry. again

2021년 6월 14일 (월) 오전 4:06, ethanwhite ***@***.***>님이 작성:

**Comment by ethanwhite** [comment]
Ok, thanks for the explanation. No problem.

If you can open a new issue that describes how they are not working for you, following the approach described above, we'll be happy to help.
