### ISSUE TITLE
Allow uses to freeze and just train regression head

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#202]
For users without access to GPUs, its pretty heavy to train the whole network. While performance will not be as good, just training the linear classifier may be enough in some cases. This would need some docs and testing. I can image a freeze flag in config that is checked when deepforest.create_trainer() is called.

**Comment by ethanwhite** [comment]
Doesn't seem like we really want to close this one.

**Comment by Al-ameen007** [comment]
hello, I wanted to become a GSoC contributor, and this seems like a good place to start, what exactly should I do?

**Comment by bw4sz** [comment]
I made a few issues that are more pertinent than this. I'm going to close, can you tell me a bit about your goals. And we can work from there.
