### ISSUE TITLE
Puzzling results during training

### ISSUE THREAD

**Issue by SailorUrano** [weecology/DeepForest#215]
**Describe the bug**
Hi, I have encountered an issue similar to what is described in issue #212. When using the model for training on a tile (which I unfortunately cannot share), I obtain ridiculously low precision and recall (in the order of 0.001). I used this same exact code last week, with the same exact tif file and annotation file, and obtained very good precision and recall (above 0.75 for both). When I open the pred_result folder, I see something very similar to what is displayed in issue #212, with all the boxes squeezed in a line at the top. 

If I simply predict on the same tile, without going through training, I obtain a reasonable result. So there's something weird happening when I train. I'm particularly puzzled because I have used this exact code with the same data for a couple of weeks and had consistently good results, so what has changed all of a sudden?

**To Reproduce**

This is a link to my Colab, which follows quite closely your Colab demo: https://colab.research.google.com/drive/1UKv5lWqqNpGvlLmDb3pLtcHx9-x6W7SQ?usp=sharing

I only changed the file names to something like "yourTrainingFile", as I cannot share the tile (however I don't believe that is the problem here)

**Environment (please complete the following information):**
 - OS: 
 - Python version and environment : 
 I'm using Google Colab as training does not work on my Windows machine

**Screenshots**
![pred result screenshot](https://user-images.githubusercontent.com/51669251/125649271-4bee9d28-e7b3-4a46-9830-62f3c443796b.PNG)

**Additional context**

Thank you for your help!

**Comment by SailorUrano** [comment]
so sorry, not sure that link works :D in case it doesn't, here's one that should:
https://colab.research.google.com/drive/1UKv5lWqqNpGvlLmDb3pLtcHx9-x6W7SQ?usp=sharing

**Comment by bw4sz** [comment]
looking into this now since more than one person has reported it. I could not reproduce in the other case and without sharing and image it is very difficult.  Can you please try with the standard package data

```
from deepforest import get_data
image_path = get_data("OSBS_029.png")
csv_file = get_data("OSBS_029.csv")
```
and confirm you get the same odd result?

**Comment by bw4sz** [comment]
can you confirm when you last ran? Looking here

https://github.com/weecology/DeepForest/commits/main

There has been no updates since June 26th

https://pypi.org/project/deepforest/#history

**Comment by bw4sz** [comment]
if you really can't share the image (i'm happy to sign whatever), run that colab and print images of

1. predict before training to show it works.
2. Visualize the a training crop to see if preprocess.split_raster works correctly.
3. Predictions after train
wrap it into a pdf and attach it here.

**Comment by SailorUrano** [comment]
I can confirm the same thing happens when I use the standard package data:
![screenshot deepforest data](https://user-images.githubusercontent.com/51669251/125690941-ced7e041-32e0-4981-bd06-26daeca9f83c.PNG)

I'll ask tomorrow at work what is required to share my tile and my annotations, and hopefully we can come to an agreement :) Otherwise I'll try what you suggest in the last comment. However, the fact that it happens also with the standard package makes it seem like the problem does not depend on my data. I'll be in touch soon!

**Comment by bw4sz** [comment]
definitely. can you link the colab you did for that last image just so we are on the exact same page. I don't need your data if we can recreate it with package data. Thanks for trying that out. Something strange going on since I cannot recreate locally? We need to get the exact commands down

```
from deepforest import main
from deepforest import get_data
from matplotlib import pyplot as plt
import os
m = main.deepforest()
m.use_release()
old = m.predict_image(path=get_data("OSBS_029.png"), return_plot=True)
m.config["train"]["csv_file"] = get_data("OSBS_029.csv")
m.config["train"]["root_dir"] = os.path.dirname(get_data("OSBS_029.csv"))
m.config["epochs"] = 1
m.create_trainer()
m.trainer.fit(m)
new = m.predict_image(path=get_data("OSBS_029.png"), return_plot=True)
fig, axes = plt.subplots(nrows=1,ncols=2, figsize=(5,5))
axes[0].imshow(old[:,:,::-1])
axes[1].imshow(new[:,:,::-1])

```

can you confirm it isn't just colab + matplotlib figsize? Also just do 1 epoch for sanity sake.

![Uploading Screen Shot 2021-07-14 at 2.36.34 PM.png…]()

**Comment by SailorUrano** [comment]
Hi, I deeply apologise, I think yesterday I wasn't quite awake, and so tested your proposition not using the data you recommended above, but rather the 2019_YELL_2_528000_4978000_image_crop2.png . I went into autopilot because that's what I had used to follow your tutorial. 
Today I used the OSBS_029.png, and obtained the same result as you, and tested using your same code. 
However, a problem persists with the YELL data. Here's a link to the Colab I used: https://colab.research.google.com/drive/1JtF0oyP0WmkGy_4cDOw0qQZ3JLjMyKOR?usp=sharing

And even more strangely, today I obtain a slight variation on what was happening before, where it says that no predictions are made after the training process. However this is the same code as yesterday, so I don't understand what changed.

Either there's something off in the way the package is pip installed on Colab (the other person in issue #212 is also using Colab and installing it the same way as me), or perhaps something happens when going through one of the step that are not done for OSBS_029.png. Perhaps when using the xml_to_annotations utility? or one of the subsequent steps. I'm stabbing in the dark here. 

So sorry again for creating confusion! However there's still clearly something weird happening, even when using the package data, so hopefully this is useful.

**Comment by SailorUrano** [comment]
And I get the same behaviour when using my own data. 0.0 for both precision and recall, and no more of the line of squeezed boxes at the top, but rather just no predictions at all. Below a screenshot of the content of my pred_result folder: 

![screenshot no prediction](https://user-images.githubusercontent.com/51669251/125768405-8abc8171-5388-4abe-9bee-ecd987b58146.PNG)

Same code as yesterday, so it just seems like perhaps this is a variation of the same behaviour as I was getting before?

**Comment by bw4sz** [comment]
Follow up here. Can you show the results of the above code. I'm trying to break down if this is a package contents issue, a interaction with google colab, or specific to the dataset. I need full code, not just output images. I'm concerned you are using the full image annotations instead of the crop annotations, but that's just a guess without full code. Let's stick to package data to make this reproducible and then test it on your own data.

**Comment by SailorUrano** [comment]
Hi, thank you for the follow-up. Sorry if this is daft, but I'm unclear on what you mean by needing the full code, is the link to colab not enough? That's all the code I ran. It feels to me like there's an issue when the package interacts with colab, but, like I said, I'm stabbing in the dark a little :D

**Comment by kristiyan-hristov** [comment]
Hi 
Today I ran the same code as before and it worked as expected after training
![image](https://user-images.githubusercontent.com/78650985/126305415-78b57971-8d97-42c6-8b8e-a76d5b1a7127.png)
Now because I don't want to lose these results I would like to save this trained model
How should I do that?
I already tried :
model.save_model(path) 
but it returns this:
![image](https://user-images.githubusercontent.com/78650985/126305715-6e4cfdc9-ca33-4251-bfc0-65e93ae24931.png)

**Comment by bw4sz** [comment]
I've run into this same problem on colab. Best to just save as normal torch

```
torch.save(model.model.state_dict(),model_path)
```

and restore

```
model = main.deepforest()
model.model.load_state_dict(torch.load(model_path))
```
