### ISSUE TITLE
'deepforest' object has no attribute 'backbone'

### ISSUE THREAD

**Issue by bmce0003** [weecology/DeepForest#223]

**Comment by bmce0003** [comment]
Description

- The error that I am getting is in trying to use the predict_image function on my own image, it is returning that the 'deepforest' object has no 'backbone' and this is coming from line 81 for the predict_image function "self.backbone.eval()"

To reproduce
from deepforest import main
m = main.deepforest()
ortho_image = get_data("C://Users//Benjamin//Desktop/Honours Project 2021/Data/ortho.tif")
m.predict_image(path = ortho_image)

Environment
I'm working in Windows 10 pro 64 bit

I apologise if I have made a simple mistake as I am quite new to python and conda and such. If you need me to provide any more information regarding my setup I can do so. Cheers.

![2021-07-19 (2)](https://user-images.githubusercontent.com/87511642/126102914-0414bada-b51b-47d4-871e-d2739ae252a3.png)

**Comment by bw4sz** [comment]
thanks for the issue. You did not use the release model, or train a new model. There is no model to use for prediction.
See 

https://deepforest.readthedocs.io/en/latest/getting_started.html#getting-started

```
from deepforest import main
from deepforest import get_data
import os
import matplotlib.pyplot as plt
model = main.deepforest()

#You are missing this line
model.use_release()

img = model.predict_image(path="/Users/benweinstein/Documents/NeonTreeEvaluation/evaluation/RGB/TEAK_049_2019.tif",return_plot=True)

#predict_image returns plot in BlueGreenRed (opencv style), but matplotlib likes RedGreenBlue, switch the channel order.
plt.imshow(img[:,:,::-1])
```

How can I make the docs, docstrings better to avoid users making this mistake in the future?
