### ISSUE TITLE
After saving the model, when restoring it from the file, I don't get the proper results

### ISSUE THREAD

**Issue by kristiyan-hristov** [weecology/DeepForest#225]
Dear developers,
Last week or so I asked you on another thread how to save my model. Today I tried what you instructed:
![image](https://user-images.githubusercontent.com/78650985/127148762-8494eec7-73ba-45d8-b561-2f049404444f.png)
But then when restoring the model I don't get the same results:
![image](https://user-images.githubusercontent.com/78650985/127148851-eba1b726-140b-4ef6-af3c-ba649d308736.png)
Do you know why that is?

**Comment by luforestal** [comment]
Hellos Cristian,  Can you maybe share this trained model? I saw this work very good on cities, I need some similar to detect urban trees. Thank you.

**Comment by bw4sz** [comment]
Can you make the colab fully reproducible, so I can see the model original image, the way you saved and then the reloaded and the final image, all together in one script. It's not possible to guess. There is a test written that confirms save and reload passes 

```
def test_save_and_reload_checkpoint(m, tmpdir):
    img_path = get_data(path="2019_YELL_2_528000_4978000_image_crop2.png")    
    m.config["train"]["fast_dev_run"] = True
    m.create_trainer()
    #save the prediction dataframe after training and compare with prediction after reload checkpoint 
    m.trainer.fit(m)    
    pred_after_train = m.predict_image(path = img_path)
    m.save_model("{}/checkpoint.pl".format(tmpdir))
    
    #reload the checkpoint to model object
    after = main.deepforest.load_from_checkpoint("{}/checkpoint.pl".format(tmpdir))
    pred_after_reload = after.predict_image(path = img_path)

    assert not pred_after_train.empty
    assert not pred_after_reload.empty
    pd.testing.assert_frame_equal(pred_after_train,pred_after_reload)

def test_save_and_reload_weights(m, tmpdir):
    img_path = get_data(path="2019_YELL_2_528000_4978000_image_crop2.png")    
    m.config["train"]["fast_dev_run"] = True
    m.create_trainer()
    #save the prediction dataframe after training and compare with prediction after reload checkpoint 
    m.trainer.fit(m)    
    pred_after_train = m.predict_image(path = img_path)
    torch.save(m.model.state_dict(),"{}/checkpoint.pt".format(tmpdir))
    
    #reload the checkpoint to model object
    after = main.deepforest()
    after.model.load_state_dict(torch.load("{}/checkpoint.pt".format(tmpdir)))
    pred_after_reload = after.predict_image(path = img_path)

    assert not pred_after_train.empty
    assert not pred_after_reload.empty
    pd.testing.assert_frame_equal(pred_after_train,pred_after_reload)
```

**Comment by kristiyan-hristov** [comment]
What do you need in order to make it fully reproducible? The training data?

**Comment by kristiyan-hristov** [comment]
For some strange reason now it works pretty well. I don't really know why last time it didn't but probably the mistake was mine. Thank you very much for the help.
Also now that I have kind of finished my project and I think my results are pretty good do you want me to send you the trained model so that you see how it works and if you are also happy with the results we can probably share it for other people in the community that will want to predict trees in urban environments.
Also one more question:
The organization I am working for wants me to write a paper about the projects and the results, so do you mind of I do that. I will of course mention the library, the algorithm and will provide links and references to the documentation and this GitHub repo. Thanks so much in advance!
