### ISSUE TITLE
Crown Detection with Name

### ISSUE THREAD

**Issue by Bognar791** [weecology/DeepForest#226]
I saw this project and I think this project is very good project for me.
I am trying to me a project what can detect tree crown with tree name.
This project can detect tree crown as well but have no function for tree name.
If I retraining model, Can I get tree name from this project?

**Comment by bw4sz** [comment]
Tree species prediction is not yet supported. If you have labels for a tree species, you can create a multi-class model, but it not supported from the use_release() function.
