### ISSUE TITLE
error GPU and TPU

### ISSUE THREAD

**Issue by gislain22** [weecology/DeepForest#228]
Saving and loading models in DeepForest

Steps
import tempfile
import pandas as pd
tmpdir = tempfile.TemporaryDirectory()
model.use_release()
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/1.0.0 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/1.0.0
img = model.predict_image(path="D:/Data_ALS/Analyses/data_brute/Drone/DSM to Gislain/mosaics/Ntui_4_5_6_transparent_mosai1.tif",return_plot=True)
model.create_trainer()
GPU available: False, used: False
TPU available: False, using: 0 TPU cores

I use Windows10 and python 3.8 version

![image](https://user-images.githubusercontent.com/87072400/127318782-405bf406-d918-4ad6-91b9-5533567641a5.png)

**Comment by bw4sz** [comment]
Please follow the bug report format, or I cannot help. I do not see an error? This is normal pytorch behavior, nothing to do with this repo. If you have a GPU or TPU it will detect them, provided you installed a GPU aware version of pytorch.  Its just letting you know there isn't a GPU or TPU. Closing for lack of documentation or obvious error.
