### ISSUE TITLE
Http Error

### ISSUE THREAD

**Issue by Bognar791** [weecology/DeepForest#229]
![Screenshot_1](https://user-images.githubusercontent.com/69195263/127356599-996e1b72-19e2-4de2-a315-171252e12266.png)
I can see this http limit error.

**Comment by bw4sz** [comment]
This is known issue, you have run the release mode so many times that github thinks you are attacking it. Usually wait five to 10 minutes or get your own github API key. What were doing where you hit this limit? Usually its something like 1000 requests per hour.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api

If this starts to be a problem on the user side, let me see if I can find a fix. That means there are way more people using this repo than expected.

**Comment by bw4sz** [comment]
I have added a check_release function to use_release if you need to don't want to check the github, this is best used in cases where you are hitting rate limit. Release 1.1.0
