### ISSUE TITLE
Multi class train and save model and load and predict_image

### ISSUE THREAD

**Issue by Bognar791** [weecology/DeepForest#233]
Could you explain or include functions to train multi class and load and predict image..
I tried with current functions but doesn't work correctly.

    m = main.deepforest(num_classes=2,label_dict={"Alive":0,"Dead":1})
    m.config["train"]["csv_file"] = get_data("testfile_multi.csv") 
    m.config["train"]["root_dir"] = os.path.dirname(get_data("testfile_multi.csv"))
    m.config["batch_size"] = 4
    m.config["train"]["fast_dev_run"] = False
    m.config["validation"]["csv_file"] = get_data("testfile_multi.csv") 
    m.config["validation"]["root_dir"] = os.path.dirname(get_data("testfile_multi.csv"))
    m.create_trainer()
    m.trainer.fit(m)
    save_dir = os.path.join(os.getcwd(),'asdf')
    results = m.evaluate(csv_file=m.config["validation"]["csv_file"], root_dir=m.config["validation"]["root_dir"], savedir=save_dir)
    print(results)
    
 I tried like this for multi class train, but it shows  "No predictions made"
And then not working train.

**Comment by bw4sz** [comment]
There isn't any error here, the multi-class train example above runs clean, its just that it is a small toy example.  You are starting from imagenet weights, not the release model, just as a guess it would take probably 10000 annotations to make a decent 2 class model starting from scratch.
