### ISSUE TITLE
convert box to shp.

### ISSUE THREAD

**Issue by gislain22** [weecology/DeepForest#234]
Hi
I would like to convert my .csv file (box) obtained with DeepForest into a .shp file where each square of my box will be considered as a polygon.
Could someone help me?

Thanks in advance.

**Comment by henrykironde** [comment]
This error is related to an old collab file we are updating that

**Comment by bw4sz** [comment]
@gislain22 if you need more help, share the google colab and I will assist, feel free to write in french, we can google translate, @henrykironde and I love doing this stuff.

**Comment by anderson-lactec** [comment]
@gislain22 , I wrote a simple function to save boxes for the geopackage. Try this:

```
def boxes_to_geofile(raster_path=None, boxes=None, geofile='',
                     layer_name='results'):

    with rasterio.open(raster_path) as dataset:
        bounds = dataset.bounds
        pixel_size_x, pixel_size_y = dataset.res
        crs = dataset.crs

    boxes["xmin"] = (boxes["xmin"] * pixel_size_x) + bounds.left
    boxes["xmax"] = (boxes["xmax"] * pixel_size_x) + bounds.left
    boxes["ymin"] = bounds.top - (boxes["ymin"] * pixel_size_y)
    boxes["ymax"] = bounds.top - (boxes["ymax"] * pixel_size_y)

    boxes['geometry'] = boxes.apply(lambda row: box(row.xmin, row.ymin,
                                                    row.xmax, row.ymax), axis=1)

    boxes = gpd.GeoDataFrame(boxes, geometry='geometry')
    boxes.crs = crs
    boxes.to_file(geofile, driver='GPKG', layer=layer_name)
```

To call the function:
```predicted_raster = model.predict_tile(raster_path=RASTER_PATH,  patch_size=600, patch_overlap=0.01)``` 
or
```predicted_raster = model.predict_image(path=RASTER_PATH)```

```boxes_to_geofile(raster_path=RASTER_PATH, boxes=predicted_raster,  geofile=GEOPACKAGE, layer_name=LAYER_NAME)```

Where:
RASTER_PATH= raster path from your image;
GEOPACKAGE= file path from geopackage (the function create this file)
LAYER_NAME= name of the layer to save in the geopackage.

You can uptade the function to save the shapefile.

I hope the help you.
