### ISSUE TITLE
Train issue

### ISSUE THREAD

**Issue by luforestal** [weecology/DeepForest#235]
Could you help me? I tried to train with custom data but doesn't work. 

I'm trying with this code:

m = main.deepforest()
m.config["train"]["csv_file"] = get_data("/DeepForest/train/images/train.csv")
m.config["train"]["root_dir"] = os.path.dirname(get_data("/DeepForest/train/images/train.csv"))
m.config['gpus'] = '4' #move to GPU and use all the GPU resources
m.config["batch_size"] = 2
m.config["score_thresh"] = 0.7
m.config["train"]['epochs'] = 100
m.config["validation"]["csv_file"] = get_data("/DeepForest/train/images/valid.csv")
m.config["validation"]["root_dir"] = os.path.dirname(get_data("/DeepForest/train/images/valid.csv"))
m.create_trainer()

Firstly: I have available 4 GPUs', but the model don't recognized them. I've the following error:

MisconfigurationException: You requested GPUs: [4]
But your machine only has: [0]

However, if I use GPU= '0' works (I think)

Secondly: When I try to create the trainer 

m.trainer.fit(m)

The follow error appear: AttributeError: 'DataFrame' object has no attribute 'image_path', I thought may be been the header but, my training data was saved without a header.

![image](https://user-images.githubusercontent.com/76424439/128368915-ee458a3d-f815-4ad1-9711-0bf92f04b2d4.png)

Thank you for the support!

**Comment by bw4sz** [comment]
Please do not skip the form when you submit an issue. In the future I will close. Start with pytorch, which is way upstream of this repo. Confirm you actually have 4 gpus, deepforest doesn't do anything outside of normal pytorch, I doubt you have installed correctly?

https://discuss.pytorch.org/t/i-have-3-gpu-why-torch-cuda-device-count-only-return-1/7245/4

```
import torch
import sys
print('__Python VERSION:', sys.version)
print('__pyTorch VERSION:', torch.__version__)
print('__CUDA VERSION')
from subprocess import call
# call(["nvcc", "--version"]) does not work
! nvcc --version
print('__CUDNN VERSION:', torch.backends.cudnn.version())
print('__Number CUDA Devices:', torch.cuda.device_count())
print('__Devices')
call(["nvidia-smi", "--format=csv", "--query-gpu=index,name,driver_version,memory.total,memory.used,memory.free"])
print('Active CUDA Device: GPU', torch.cuda.current_device())

print ('Available devices ', torch.cuda.device_count())
print ('Current cuda device ', torch.cuda.current_device())
```

If you read the docs, you can see that the format for the csv does have a header, and that image_path is the relative, not absolute path.

https://deepforest.readthedocs.io/en/latest/getting_started.html#training
