### ISSUE TITLE
Bounding boxes not overlaying on Image and prediction

### ISSUE THREAD

**Issue by Ruphai** [weecology/DeepForest#241]
Dear Developers, 

I tried visualizing the output of the `predict_image()`  for my local data but it does not display the bounding box along with the image. 

Here are the screen grab of the set-up leading to the implementation of the predict_image:

![Iss1](https://user-images.githubusercontent.com/59208190/128881922-1818b3b2-3216-4b3c-a079-905957bc5b59.PNG)

![Iss2](https://user-images.githubusercontent.com/59208190/128881934-0b01ae8a-4754-4bd6-972c-6fa365d3c262.PNG)

![Iss3](https://user-images.githubusercontent.com/59208190/128881959-8f1b89d3-dc83-4d3f-9142-8c69fa2d49f0.PNG)

![Iss4](https://user-images.githubusercontent.com/59208190/128881970-d96ac8e8-8a56-43d3-a7a2-18d6cb3cdac5.PNG)

So, it displays just the image but does not display the bounding box. Is there something I might be missing? 

Thank you.

**Comment by ethanwhite** [comment]
Does the same issue occur with the current release or only with the new pull request?

**Comment by ethanwhite** [comment]
Also, @Ruphai, do you see the same behavior with the build in example image? You can check by running:

```python
from deepforest import main
from deepforest import get_data
import matplotlib.pyplot as plt
model = main.deepforest()
model.use_release()

image_path = get_data("OSBS_029.png")
boxes = model.predict_image(path=image_path, return_plot=True)
plt.imshow(boxes[:,:,::-1])
plt.show()
```

**Comment by Ruphai** [comment]
No, I am not using the pull request in this case. I had commented out the additional variables. It's the current release. 

The built-in example works fine. Do you think it has something to do with the image format?

**Comment by ethanwhite** [comment]
> Do you think it has something to do with the image format?

That seems likely. Is it possible for you to share the image (either publicly or privately)?

**Comment by Ruphai** [comment]
Sure, I can share it with you. I just sent you an email.

**Comment by Ruphai** [comment]
Thank you @ethanwhite. It's displaying properly at my end now. Thanks for adding this new functionality.

**Comment by ethanwhite** [comment]
Glad to hear it. Good luck with your work!
