### ISSUE TITLE
Negative Samples error

### ISSUE THREAD

**Issue by sethhenrymorgan** [weecology/DeepForest#243]
Following the instructions in the Getting Started doc, I wanted to add some negative samples to improve provision a bit (I was picking up some houses as tree crowns, so I cut out some images with only houses and no trees). I appended the following to my training annotations:

```
neg_annotations = pd.DataFrame([["Nampula_B_2_R21C6_ClipL_house.tif",0,0,0,0,"Tree"],
                                ["Nampula_B_2_R21C6_ClipL_house2.tif",0,0,0,0,"Tree"],
                                ["Nampula_B_2_R21C6_ClipL_house3.tif",0,0,0,0,"Tree"]], 
                               columns=['image_path','xmin','ymin','xmax','ymax','label'])
train_annotations = train_annotations.append(neg_annotations)
```

But when I ran the trainer I get an error.

```
#initialize the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
m.config["score_thresh"] = 0.9
m.config["nms_thresh"] = 0.2
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training 
m.create_trainer()
#load the lastest release model 
m.use_release()
m.trainer.fit(m)


ValueError: x_max is less than or equal to x_min for bbox (0.0, 0.0, 0.0, 0.0, 0).
```

**Comment by ethanwhite** [comment]
This is something that @bw4sz's been working on. See #216 and the commits from July 23rd. If you're using the current release you can try to update to the development version and see if that helps:

```
pip install git+https://git@github.com/weecology/DeepForest.git
```

but it's not clear from #216 if everything is working as expected yet or not. @bw4sz is offline for a bit but can provide more insight when he returns.

**Comment by sethhenrymorgan** [comment]
Thanks for your response! I updated to the development version and instead of the error message above, the training completed, but then at the evaluate stage it said No predictions made. See below. Must still be hanging up somewhere. 

No predictions made

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by ethanwhite** [comment]
Thanks @sethhenrymorgan. This seems related to the current status of the discussion in #216 so let's wait until @bw4sz is around and see if he can help out.

**Comment by sethhenrymorgan** [comment]
Sounds good. I'll follow that discussion as well. Thanks!

**Comment by bw4sz** [comment]
Closing this is in favor of the other issue, let's consolidate and talk there.
