### ISSUE TITLE
Getting Started (no plot?)

### ISSUE THREAD

**Issue by bwilder95** [weecology/DeepForest#252]
Hello!

I was trying to follow along on the getting started page (https://deepforest.readthedocs.io/en/latest/getting_started.html#prebuilt-models) and I ran into the following error.

```
Reading config file: /home/brent/home/PhD/.venv/lib/python3.8/site-packages/deepforest/data/deepforest_config.yml
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/1.0.0 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/1.0.0
/home/brent/home/PhD/.venv/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
[INFO] Script completed after 0:00:01.437660
```

I thought this may be just a warning that torch could be throwing, however, my script is failing to produce a plot. My code looks like
```
from deepforest import main
from deepforest import get_data
import matplotlib.pyplot as plt
model = main.deepforest()
model.use_release()

image_path = get_data('OSBS_029.png')
img = model.predict_image(path=image_path, return_plot = True)
plt.imshow(img[:,:,::-1])

```

I am working in Windows Subsystem for Linux (WSL-2) within a python virtual environment (python 3.8.10) in Visual Studio Code. Any help would be greatly appreciated.

Best,
Brent

**Comment by ethanwhite** [comment]
Hi @bwilder95 - glad you're checking out DeepForest!

The warning is just that we're using a somewhat early stage feature, so nothing to worry about.

I think the lack of plot is just Python's plotting, which is sometimes very conservative about actually showing you something. Try adding `plt.show()` to the bottom of your code.

**Comment by bwilder95** [comment]
Hi @ethanwhite thanks for the quick reply! I tried adding `plt.show()` but still got no output. However, when I run `plt.savefig()` it __does__ work! Not sure what's happening on my system but seems to be working fine as long as I don't try to display the plot.

**Comment by ethanwhite** [comment]
Glad to hear things are working. Sounds like a general issue with Python plotting since `img` is just a NumPy array that's then getting plotted, but if you can plot other things in your development environment feel free to reopen.
