### ISSUE TITLE
Visualizations of Predictions for entire image

### ISSUE THREAD

**Issue by PravinM83** [weecology/DeepForest#259]
**Describe the bug**
Currently Not able to get the Visualizations of Predictions for the entire image.

**To Reproduce**
Re-trained the DeepForest model, using one image.
![image](https://user-images.githubusercontent.com/88822556/139663669-e6cb7328-abd5-493a-b32b-134fe467b43c.png)
Here, 
I am able to See the Precision, Recall Values, also able to see Visualizations for small crops in the pred_result folder. 
Is there any way to get **visualizations for an entire input image** in addition to small crops?

**Environment (please complete the following information):**
 - OS: Used Google Colab
 - Python version and environment : 

**Screenshots**

**Additional context**

**Comment by ethanwhite** [comment]
You should be able to use either [`predict_image()`](https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-single-image) or [`predict_tile()`](https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-tile) to get the visualizations for the retrained model.

Also, just in the last week we've added the bounding box coordinates to the `results["results"]` object, so if you install the current version of `main` from the repository it will expose that information there as well:

```bash
pip install git+https://git@github.com/weecology/DeepForest.git
```

**Comment by bw4sz** [comment]
Can we close here?

**Comment by PravinM83** [comment]
Yes, We can close this issue.

**Comment by PravinM83** [comment]
The issue is resolved so, closing the ticket.
