### ISSUE TITLE
TIF / CSV file? Which one should I input to predict a single image?

### ISSUE THREAD

**Issue by philipperemy** [weecology/DeepForest#260]
Hey,

I want to predict on a single image with the pre-trained model.

How can I do that? You input a TIF file as a CSV file. When I do that it does not work:

Predict a single image

```python
from deepforest import main
csv_file = '/Users/benweinstein/Documents/DeepForest/deepforest/data/OSBS_029.tif'
df = trained_model.predict_file(csv_file, root_dir = os.path.dirname(csv_file))
```

**Comment by ethanwhite** [comment]
Hi @philipperemy - welcome to the DeepForest community!

To predict single images you want to use either [`predict_image`](https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-single-image) or [`predict_tile`](https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-tile] depending on the size of the image. `predict_tile` is for images that are too big to fit into memory and therefore need to be predicted in chunks. Take a look at those docs and let us know if you need any more help.

**Comment by philipperemy** [comment]
@ethanwhite thank you very much. It solved my problem.

**Comment by ethanwhite** [comment]
great! glad to hear it
