### ISSUE TITLE
Multi-class classification model training issue

### ISSUE THREAD

**Issue by nikiemapp** [weecology/DeepForest#262]
I know this might be a bit outside the scope of the current version of Deepforest but I am interested in using it for multi-class (i.e. two classes) classification. 

When training a model with two classes, the process  runs for just one epoch and then stops (even when set to run more than one epoch) . When evaluating the model on my validation set or making a prediction on a new image, I get no results. Something must certainly be wrong with my codes shown below. 

Note, I have been using this wonderful package (many thanks to the authors) for individual tree detection from forest harvest sites as part of our forest renewal success evaluation. I see the potential of the model to detect tree genus (.i.e. deciduous vs coniferous) and even tree species from previously harvested forest sites but multi-class classification would be the best way to go.
![image](https://user-images.githubusercontent.com/66796730/139999239-27cb225d-4c96-4f6e-ad5c-a1b68abb4ff0.png)

![image](https://user-images.githubusercontent.com/66796730/139999324-c056e54f-ce1f-4052-97fb-9cf0af4a2ffc.png)

**Comment by ethanwhite** [comment]
Hi @nikiemapp - while this isn't something we're actively supporting at the moment we are using deepforest in multi-class prediction ourselves (on birds, not trees). In general your code looks good to me. I think the reason you're only seeing a single epoch of training is the  `m.config["train"]["fast_run_dev"] = True` line, which only runs a single batch of training for testing/debuggin.

In my experience with the multiclass models it's not uncommon to get no predictions with only a single epoch of training, so I'd recommend dropping the `fast_run_dev` line and running for longer to see what happens.

Also, if you happen to be hyperspectral data you may be interested in checking out our new project doing species classification in trees using hyperspectral data: https://github.com/weecology/DeepTreeAttention

**Comment by ethanwhite** [comment]
My pleasure. I think this current error is part of #261. Can you try running

```bash
pip install --upgrade deepforest albumentations==0.5.1 pyyaml
```

to change the version of albumentations.

**Comment by nikiemapp** [comment]
This solved the issue. Thanks again
