### ISSUE TITLE
What loss functions are used in DeepForest?

### ISSUE THREAD

**Issue by landkwon94** [weecology/DeepForest#271]
Hello Sir, I have some questions while using DeepForest Python package :)

I learned that DeepForest is using RetinaNet and ResNet for backbone network.

Also I learned that both network is using SGD for optimizer.

Then, what loss functions are used in DeepForest package?

I know that RetinaNet is using Focal loss, but what loss function is used for ResNet-50?

Thank you so much for your nice package :)

I will wait for your reply!

**Comment by ethanwhite** [comment]
Hi @landkwon94 - welcome to the DeepForest queue!

ResNet-50, and therefore DeepForest, use Focal loss.

**Comment by landkwon94** [comment]
Thank you so much for your comments!
I really appreciate it :)

**Comment by ethanwhite** [comment]
Happy to help!
