### ISSUE TITLE
Retraining: transfer learning or from scratch?

### ISSUE THREAD

**Issue by EdwardHiscoke** [weecology/DeepForest#275]
Hi DeepForest Team, 
I recently came across DeepForest and its datasets and would like to thank you for the great work you have put into them 
I have started experimenting with a few predictions on some Swedish coniferous forests at 10cm resolution with what looks to me like surprisingly good results using the included model. The evaluation dataset and DeepForest look great and I'm hoping to make use of them in a project. But I'm novice at using deep learning models and have several questions about retraining and multi-classing with  DF that you perhaps could help me with or just point me in the right direction. To increase the discoverability of these questions for other users I have spread them into multiple issues. 

The documentation says great improvements can be made by adding ones own datasets. Does one have to retrain the model from scratch or does it allow for transfer learning to add the new learning samples?

**Comment by bw4sz** [comment]
Transfer learning for sure. Training from scratch requires thousands of trees (and millions of weak labels, see cited papers in repo)

**Comment by EdwardHiscoke** [comment]
Thank you for the extra info!
