### ISSUE TITLE
DeepForest or DeepTreeAttention

### ISSUE THREAD

**Issue by EdwardHiscoke** [weecology/DeepForest#277]
I'm looking into multiclass detection for detecting genus deciduous/coniferous and the possibility of classifying species. The documentation states that multiclassing  is possible using DF, but what is your experience with multiclassing in practice? And would you recommend multiclassing in the same retrained DF model or cookie-cutting out detected trees and doing species classification using a separate specialized model (which I believe DeepTreeAttention does)?

Or is multiclassing in DF not a good solution and should I instead attempt to use DeepTreeAttention instead?

**Comment by bw4sz** [comment]
I would definitely not use DeepTreeAttention yet. It is optimized for HSI data. You should do fine in DeepForest. Please close when ready and open specific issues, I saw you posted another, let me have a look.
