### ISSUE TITLE
Warnings about "Image type is {}" and "torch.meshgrid: in an upcoming release"

### ISSUE THREAD

**Issue by EdwardHiscoke** [weecology/DeepForest#280]
**Describe the bug**
Hi, DeepForest is working just fine, but I have a couple warnings popping up that I'm not sure how to adress. Is it my environment that isn't quite right or is there something else that needs updating?
The warnings I receive are when calling predict_tile are:

…/python3.9/site-packages/deepforest/predict.py:34: UserWarning: Image type is {}, transforming to float32. This assumes that the range of pixel values is 0-255, as opposed to 0-1.To suppress this warning, transform image (image.astype('float32')
 
…/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)

**To Reproduce**
Run predict_tile() with any settings.

**Environment (please complete the following information):**
 - DeepForest 1.1.3
 - OS:  Mac OS BigSur 11.6
 - Python version and environment : Plain old vanilla Python 3.9.4 using Pyenv and Poetry 1.1.11 for package management

**Screenshots**

**Additional context**
Apart from the warning, everything works just fine :)

**Comment by ethanwhite** [comment]
First warning - . This is just a check to make sure that the pixel data is encoded like the model expects them to be. Did you try the approach recommended in the warning of explicitly setting the image type to 'float32'?

Second warning - that's upstream of us, so nothing to worry.

**Comment by bw4sz** [comment]
I don't believe there is anything to worry about here. Our policy has been to not suppress upstream warnings.
