### ISSUE TITLE
Examples of best way to convert multi-band geotiff to suitable RGB image for tree detection? Any particular parameter settings, etc?

### ISSUE THREAD

**Issue by eriklindquist** [weecology/DeepForest#281]
Do you have examples of how to convert multi-spectral satellite imagery to a suitable RGB format for processing with DeepForest? I have been using gdal to convert from multi-band tif (Planet imagery, Sentinel-2 imagery) to JPG. Is this a suitable way to do this? Do you recommend any specific creation parameters? 

I'm having trouble getting good results so far. Granted, I am continuing to try different DeepForest parameters to accommodate the coarser resolution of my input imagery. But, I would like to make sure from the start I am using a proper input format of the data.

Thanks.

**Comment by ethanwhite** [comment]
Hi @eriklindquist - We haven't converted multi-spectral to RGB for this purpose, but I think fundamentally there are two approaches that make sense:

1. Just convert to RGB (or as close as you can get), which is likely what gdal is doing (but I don't know for sure). This will make trees appear in the same color space the model is built on which should make direct application and transfer learning easier.
2. Alternatively, you could look for band combinations that give you the clearest distinction between trees and background. This would require more retraining though (and potentially kind of deep in the network) so personally I'd lean towards (1) at the moment.

That said, assuming that you're currently converting to something close to RGB, I suspect that (as you mention) the issue really is more about resolution than that conversion.

**Comment by eriklindquist** [comment]
Yep...sorry. Was trying some things to see if I could contribute but taking longer than I thought. Will close.
