### ISSUE TITLE
Pass config path into constructor

### ISSUE THREAD

**Issue by a-orn** [weecology/DeepForest#283]
**Please describe A feature you would like to be added.**
When comparing models I often have multiple config files, not always in the root directory.

**Describe the solution you'd like**
I'd like to add a path argument to the `deepforest()` constructor to override the path on [L40](https://github.com/weecology/DeepForest/blob/main/deepforest/main.py#L40)

**Alternatives you've considered**
Currently I'm manually overriding it:

```python
m = deepforest()
m.config = utilities.read_config(config_path)
m.create_model()
```

**Comment by ethanwhite** [comment]
Thanks for the suggestion @a-orn! Can you take a look at #284 and see if that covers what you're looking for?

**Comment by a-orn** [comment]
This looks awesome, thanks!
