### ISSUE TITLE
GPU detected but not usedf despite setting on model for training

### ISSUE THREAD

**Issue by Ciaran1981** [weecology/DeepForest#286]
Hi  - what a great lib - thanks for making this available for researchers. Not sure if this is a bug per se.

When setting up a model for training as per the documentation  after the executing of:

`model.create_trainer()`

The following warning is returned:
```
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/ciaran/anaconda3/envs/DeepForest/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1580: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`
```
I can train and predict fine, but the training is CPU borne despite earlier moving it to GPU as per the documentation.

Can you suggest a solution?

Thanks

**Comment by ethanwhite** [comment]
The `model` object probably isn't being told that you want to use the GPU. This information can be provided by either

1. Add a copy of [`deepforest_config.yml`](https://github.com/weecology/DeepForest/blob/main/deepforest_config.yml) to  the root directory of your project. Then modify that copy to add a 1 to the gpu line: `gpus: 1`.
2. Adding the following line to your code after creating the model but before creating the trainer: `model.config["gpus"] = 1`

Let me know if that doesn't solve the issue.

**Comment by ethanwhite** [comment]
If that doesn't work can you provide a minimal reproducible example (a small piece of code that when you run it reproduces the issue) since that will make it easier for us to understand what's going wrong.

**Comment by easz** [comment]
something like this?
~~~
from deepforest import main

m = main.deepforest()
m.config["gpus"] = 1
m.create_trainer()
~~~

**Comment by easz** [comment]
@ ethanwhite  
is `m.to("cuda")` (i.e. `pytorch.to()`) relevant to training process?

**Comment by bw4sz** [comment]
No, you do not need to pass to device, it is handled inside the pytorch dataloader. I've never tested -1 for all GPUs, but it gets passed to the pytorch lightning Trainer, it looks like you are correct.

https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#
```# no auto selection (picks first 2 gpus on system, may fail if other process is occupying)
trainer = Trainer(gpus=2, auto_select_gpus=False)

# enable auto selection (will find two available gpus on system)
trainer = Trainer(gpus=2, auto_select_gpus=True)

# specifies all GPUs regardless of its availability
Trainer(gpus=-1, auto_select_gpus=False)

# specifies all available GPUs (if only one GPU is not occupied, uses one gpu)
Trainer(gpus=-1, auto_select_gpus=True)```

**Comment by bw4sz** [comment]
Please close when ready.

**Comment by Ciaran1981** [comment]
> The `model` object probably isn't being told that you want to use the GPU. This information can be provided by either
> 
>     1. Add a copy of [`deepforest_config.yml`](https://github.com/weecology/DeepForest/blob/main/deepforest_config.yml) to  the root directory of your project. Then modify that copy to add a 1 to the gpu line: `gpus: 1`.
> 
>     2. Adding the following line to your code after creating the model but before creating the trainer: `model.config["gpus"] = 1`
> 
> 
> Let me know if that doesn't solve the issue.

Hi,

Sorry for the delay - doing this seemed to work. 

Cheers!

**Comment by ethanwhite** [comment]
Glad you got it working @Ciaran1981. Thanks for reporting back!
