### ISSUE TITLE
new conda package for the latest version of deepforest

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#288]
**Please describe A feature you would like to be added.**
The available [conda package](https://anaconda.org/conda-forge/deepforest) is pretty old, would you also update it? or is the conda package managed independently from your work?

**Describe the solution you'd like**
latest deepforest version also in conda

**Describe alternatives you've considered**
use `pip` at the moment

**Additional context**
-

**Comment by bw4sz** [comment]
I've found the conda version much harder to manage. @henrykironde let's give it another go. There was something blocking it upstream of us.

**Comment by bw4sz** [comment]
You can follow along here

https://github.com/conda-forge/deepforest-feedstock/pull/24

**Comment by bw4sz** [comment]
Updated, please give a try and close when ready. 
https://github.com/conda-forge/deepforest-feedstock

**Comment by ethanwhite** [comment]
@easz - does the conda installation work for you now? (we've been having some issues when testing locally)

**Comment by easz** [comment]
let me check again....

**Comment by easz** [comment]
btw, I had to install `albumentations` manually after `conda create`. The `albumentations` is probably missing in `deepforest-feedstock/recipe/meta.yaml`. I can try to make another PR.

**Comment by ethanwhite** [comment]
Thanks @easz, that would be great.

It looks like I have a working version of this now on Linux (Ubuntu 21.10), but it's finicky. This works:

```bash
mamba create -n deepforest python=3 deepforest albumentations -c conda-forge
```

But this doesn't:

```bash
mamba create -n deepforest python=3
conda activate deepforest
mamba install deepforest albumentations -c conda-forge
```

And it's a only a CPU build.

**Comment by easz** [comment]
@ethanwhite 
Actually I have the same issue with installation of `albumentations` on Windows. :P
I guess that conda has some issues with resolving its dependency.

And about pytorch cuda: on Windows it is installed automatically correctly..
(have to try again on linux..)

another problem on Windows: I have to upgrade `pytorch-lightning` afterwards.

did you also try this at first:
`conda create --name myenv pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
and then install the rest in the env
`conda activate myenv`
`conda install deepforest`

anyway I will try to make a PR and see if it works better

**Comment by ethanwhite** [comment]
Thanks @easz!

This incantation seems to work consistently on Linux:

```bash
mamba create -n deepforest python=3 pytorch torchvision cudatoolkit=10.2 -c pytorch
conda activate deepforest
mamba install deepforest albumentations -c conda-forge
```

Once https://github.com/conda-forge/deepforest-feedstock/pull/29 goes in we should be able to drop the albumentations part and then as long as this is working on other OSs I think we can update the install docs and call this good.

**Comment by bw4sz** [comment]
@ethanwhite can you make a PR for the docs change for what works for you and then we can close?

**Comment by ethanwhite** [comment]
PR is in and everything is working so closing this issue.
