### ISSUE TITLE
Initial model to load for multi-class training

### ISSUE THREAD

**Issue by pbugnet** [weecology/DeepForest#290]
I'm trying to train a deepforest model with multiple tree classes. 
Do I need to start from scratch or can I use the latest release as a starting point, even though it's one-class only?
If so, do I need to modify the number of classes in some way or do I just need to provide annotation files with the required classes?
I couldn't find this in your documentation.
Thanks

**Comment by ethanwhite** [comment]
Hi @pbugnet  - welcome! You can leverage transfer learning for detection while shifting to a multi-class model. We're currently using the following code to do this:

```python
model = main.deepforest(num_classes=len(train.label.unique()), label_dict=label_dict)
deepforest_release_model = main.deepforest()
deepforest_release_model.use_release()
model.model.backbone.load_state_dict(deepforest_release_model.model.backbone.state_dict())
model.model.head.regression_head.load_state_dict(deepforest_release_model.model.head.regression_head.state_dict())
```

This  creates a new model with the appropriate number of classes, but then uses the backbone and regression head from the pretrained model to transfer learning about tree detection and tree related features.

*Note: this code is ported from work we're doing on birds, not trees, and the translation hasn't been tested directly*

**Comment by pbugnet** [comment]
Great! Thanks for the nice work on this project.

**Comment by bw4sz** [comment]
Should this go in docs? Or still too new and untested?

**Comment by pbugnet** [comment]
Not yet tested on my side.

**Comment by ethanwhite** [comment]
> Should this go in docs? Or still too new and untested?

This is what we've had running for Everglades for the last couple of months, so I think the answer is yes, once this particular version of the code has been run to make sure there aren't any typos in my translation.

**Comment by pbugnet** [comment]
Hi Ben. Could you please tell me more about the locations of the sites that were used for the DeepForest pre-trained model? Are they spread out all over the US or from a specific state. I wish to use DeepForest on canadian sites and would like to make sure of the variability of trees used for training

Thank you and congrats on this project.

Pierre

Pierre Bugnet M. Sc.
Spécialiste télédétection
Remote Sensing Specialist
***@***.***<https://effigis.com>
T       1 514 495-6500, 225
T       1 888 495-6501
4101, rue Molson, bur. 400, Montréal QC H1Y 3L1, Canada


This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by bw4sz** [comment]
Hey Pierre

You can see details here:
[Methods Ecol Evol - 2020 - Weinstein - DeepForest  A Python package for RGB deep learning tree crown delineation.pdf](https://github.com/weecology/DeepForest/files/8027793/Methods.Ecol.Evol.-.2020.-.Weinstein.-.DeepForest.A.Python.package.for.RGB.deep.learning.tree.crown.delineation.pdf)

Without seeing a sample image, it is hard to know, but in general, its image resolution and quality which are the barriers, rarely is it forest type that is the challenge. Make a separate issue with example predictions if you need help.

**Comment by bw4sz** [comment]
Hey Pierre

You can see details here:
[Methods Ecol Evol - 2020 - Weinstein - DeepForest  A Python package for RGB deep learning tree crown delineation.pdf](https://github.com/weecology/DeepForest/files/8027793/Methods.Ecol.Evol.-.2020.-.Weinstein.-.DeepForest.A.Python.package.for.RGB.deep.learning.tree.crown.delineation.pdf)

Without seeing a sample image, it is hard to know, but in general, its image resolution and quality which are the barriers, rarely is it forest type that is the challenge. Make a separate issue with example predictions if you need help.
