### ISSUE TITLE
suggestion on training large dataset regarding to insufficient GPU memory

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#291]
I try to train models on GPUs and immediately encounter "Cuda out of memory" problem.
My training images are about 1200x1200px (0.5m ~ 1.0m aerial resolution)
For each image there can be up to 2000 bbox for Tree labels. 
My GPU has only about 5G memory.

is there any handy function in deepforest to handle such situation?
splitting training image and annotation automatically? (does it make sense due to the image resolution?) or incrementally trainer.fit on large samples? 

one "workaround", which I am not sure if it is feasible or correct w.r.t. model training, may be to separate all tree labels in several csv containing only about 300 Tree label boxes (or any small number).

~~~
model = main.deepforest()
model.use_release()  # load the pre-trained model and train it with new data
model.config["workers"] = 1
model.config["gpus"] = 1
model.config["epochs"] = 1
model.config["train"]["fast_dev_run"] = True
model.config["train"]["root_dir"] = IMG_DIR # training images
for annotation in glob(ANNOTATION_DIR):
    model.config["train"]["csv_file"] = annotation
    model.create_trainer() # create a new trainer to fit the model again
    model.trainer.fit(model)
~~~

thanks for any suggestion!

**Comment by bw4sz** [comment]
Interesting. We have not had to optimize for GPU memory, this has not come up before. I think you want to use 

https://deepforest.readthedocs.io/en/latest/source/deepforest.html#deepforest.preprocess.split_raster

preprocess.split_raster  to divide your tiles into smaller pieces. The deepforest baseline model is 10cm at 400px crops. There is no exact science on cross-resolution fine tuning. But I'm going to guess 1000px crops for 50cm data is a good guess.

I'm going to add a section on this to docs with an example. Something like

```
def test_split_raster(config, tmpdir):
    """Split raster into crops with overlaps to maintain all annotations"""
    raster = get_data("2019_YELL_2_528000_4978000_image_crop2.png")
    annotations = utilities.xml_to_annotations(get_data("2019_YELL_2_528000_4978000_image_crop2.xml"))
    annotations.to_csv("{}/example.csv".format(tmpdir), index=False)
    #annotations.label = 0
    #visualize.plot_prediction_dataframe(df=annotations, root_dir=os.path.dirname(get_data(".")), show=True)
    
    annotations_file = preprocess.split_raster(path_to_raster=raster,
                                               annotations_file="{}/example.csv".format(tmpdir),
                                               base_dir=tmpdir,
                                               patch_size=500,
                                               patch_overlap=0)

    # Returns a 6 column pandas array
    assert annotations_file.shape[1] == 6
```

**Comment by easz** [comment]
thanks for the advice. The method `deepforest.preprocess.split_raster` is very helpful.

The most images I have are not better than 0.6m resolution and contain large amount of small trees (e.g. young urban trees), therefore I try to begin with 1200px initially.

I will give it a try with eventually smaller windows but I am still afraid that the large amount (e.g. 1k) of Tree labels causes large GPU memory usage, not the size of image itself. Just a guess. I am still a novice in deep leaning with pytorch and co..

**Comment by easz** [comment]
actually it could done on-the-fly in the `predict_tile` as well as `dataset.TreeDataset` (similar to predict_tile on large image).  I can make a PR later.
