### ISSUE TITLE
No predication can be made after training

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#293]
after training existing release model I still did not see any improvement on detection result. Therefore I tried to just train the original model (nevertheless still a pre-trained retinanet_resnet50_fpn) to see if my training process actually works.
 
my code:
~~~
model = main.deepforest()
#model.use_release()   # not use pre-trained model yet

## train on CPU
model.config["workers"] = 4   
model.config["batch_size"] = 6
model.config["epochs"] = 500      
model.config["train"]["preload_images"] = False
model.config["train"]["root_dir"] = IMG_DIR
model.config["train"]["csv_file"] =  ANNOTATION_FILE
model.create_trainer()
model.trainer.fit(model)

# predict
result = model.predict_tile(image=TEST_IMG, return_plot=True)
~~~

but I got 
~~~
No predictions made, returning None
~~~

- is there any recommendation to troubleshooting/debug?
- how many epochs did you need during the first ever training?
- will training with validation data indicate when it is good enough? (I will try it anyway)
- or something wrong with my training images? they are 0.6m resolution and I have tried both 512px and 1000px size.

my training images with annotation look like this.
![image](https://user-images.githubusercontent.com/968464/150361031-2d55ae10-f880-4403-9ab8-9dadfcb690d4.png)

btw, this is an example of prediction result with your out-of-box pre-trained NEON model. Not too wild...

![image](https://user-images.githubusercontent.com/968464/150361650-bc305a19-d818-465c-af7b-10d23d7abeb0.png)

**Comment by easz** [comment]
some positive feedback from me.

the initial idea from me to re-train the network from scratch (or from pre-trained RetinaNet) is not feasible, since it would require a huge amount training data and iterations. (@bw4sz  how many training data did you have from NEON? 100 million samples !?) My attempt with just few epochs and pretty small amount of samples would definitely fail.

My another attempt is to further train deepforest release model with 10 epochs and roughly 30k tree samples (mediocre quality w.r.t. size and resolution without careful preprocessing yet). The training images are 400x400px.  It turns out the model can be improved effectively.

prediction result with pre-trained deepforest model: (false-positive on roof top, missing small trees)
![image](https://user-images.githubusercontent.com/968464/150513576-66d4be72-75e1-42ec-a295-d3c82da8897a.png)

prediction result after further training on another 30k trees in urban context:
![image](https://user-images.githubusercontent.com/968464/150513720-0da4ba46-0918-4364-ae98-955c107d7612.png)


I will close the bug after some more experiments.

**Comment by bw4sz** [comment]
Are there are changes to docs we can make to this clearer?

**Comment by easz** [comment]
It is probably not DeepForest specific but rather general practice applicable to deep learning.

What I learned from my first experiment:

1. when a model is trained from scratch (e.g. no `use_release()`), logging can be very useful to see how learning progresses.

~~~
model.config["epoch"] = ...
model.config["validation"]["root_dir"] = ...
model.config["validation"]["csv_file"] = ...
model.config["validation"]["val_accuracy_interval"] = N # evaluate after every N epochs (to show precision, recall rate and etc.)
model.create_trainer(self, logger=TensorBoardLogger("logDir")) # enable logging in tensorboard
model.trainer.fit(model)
~~~

2. If small objects (e.g. in a urban scene) need to be detected, a smaller window size (i.e. `patch_size`) is preferred.  Such windows size is particularly essential during training and the default 400px size is a pretty good starting point. Sometimes trial and error is necessary. 

Maybe something to put in FAQ
