### ISSUE TITLE
num_classes usage is not consistent with torhcvision's doc

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#295]
**Describe the bug**

There was doc fix in torchvision https://github.com/pytorch/vision/pull/4132 for the issue https://github.com/pytorch/vision/pull/4132 (@bw4sz you were also in the discussion :) )

Basically the parameter `num_class` in RetinaNet should include the background.
~~~
num_classes (int): number of output classes of the model (including the background).
~~~

if so, then the deepforest.ctor seems be wrong with `num_classes=1`
https://github.com/weecology/DeepForest/blob/4f787bed481bc9184937383823e017c0942b4fca/deepforest/main.py#L23

I assume
~~~
 def __init__(self, num_classes=2, label_dict = {"_background_":0, "Tree":1}, transforms=None, config_file='deepforest_config.yml'): 
~~~

**Comment by bw4sz** [comment]
This is done internally. That was the outcome of that thread. num_classes if the number of classes NOT including the background. I don't see a reason to align with torchvision here, most ecologists do not have the experience with these tools and num_classes = 2 for a single annotated class would only lead to confusion.
