### ISSUE TITLE
Are there any species annotation data available in the NEON Crowns dataset?

### ISSUE THREAD

**Issue by EdwardHiscoke** [weecology/DeepForest#297]
According to the documentation the current NEON Crowns dataset does not currently contain any classes other than "Tree". We have started annotating our own localised multi-class training set for pine/spruce/deciduous and wonder if there are any other known species annotations (sub sets of NEON?) for multi-class training using the same classes or thereabouts available for the northern US?
I hope it's not inappropriate, but tips for any source of annotations are welcome.

**Comment by ethanwhite** [comment]
Totally appropriate @EdwardHiscoke! NEON does have geolocated field stems with species IDs that can be associated with the remote sensing and used for multi-class work. We are using them in https://github.com/weecology/DeepTreeAttention if you want to see how we're currently doing that. If you have any questions once you've taken a look an issue over in that repo would be a good place to chat.

**Comment by EdwardHiscoke** [comment]
That sounds most interesting. I'll get over to the attention project and check it out. Thanks!
