### ISSUE TITLE
missing variables in  DeepForest/deepforest/data/deepforest_config.yml 

### ISSUE THREAD

**Issue by saadmazouzi** [weecology/DeepForest#300]
**Describe the bug**
In the  DeepForest/deepforest/main.py we find :
in the line 169 self.config["train"]["preload_images"] -> which mean the deepforest_config should contain it but it's not the case
also in the line 413 self.config["validation"]["val_accuracy_interval"] == 0  we need to add the val_accuracy_interval in the config file 

**To Reproduce**

`m= main.deepforest()` 
` m.config['gpus'] = '-1' #move to GPU and use all the GPU resources` 
` m.config["train"]["csv_file"] = annotations_file` 
` m.config["train"]["root_dir"] = os.path.dirname(annotations_file)` 
` m.config["score_thresh"] = 0.4` 
` m.config["train"]['epochs'] = 2` 
` m.config["validation"]["csv_file"] = validation_file` 
` m.config["validation"]["root_dir"] = os.path.dirname(validation_file)` 

` m.create_trainer()` 
` m.use_release()` 
` start_time = time.time()` 
` m.trainer.fit(m)#there is the probleme` 
` print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds ---")` 

**Environment (please complete the following information):**
 - OS: windows
 - Python version and environment : 3.7 and google colab

**Screenshots**
![issue1](https://user-images.githubusercontent.com/98532815/151690393-333a1369-1003-46d4-9e24-5e6b10ec2f2a.PNG)
![issue2](https://user-images.githubusercontent.com/98532815/151690441-0f2c6054-3151-468e-af71-5b6cbfaf1a0a.PNG)

**Additional context**
we can fix it just by adding to the config file  this two missing config 
or just before every training we need to add this two lines  :

m.config["train"]["preload_images"] = "" 
m.config["validation"]["val_accuracy_interval"] = 5

**Comment by bw4sz** [comment]
What version of deepforest do you have? Looking on the git repo, these values already exist? 

https://github.com/weecology/DeepForest/blob/0c7c881ada5e01a3fc33827b0eeffa96265680eb/deepforest_config.yml#L27

One idea is when you do 
```
pip install --upgrade
```

we need to make sure package data gets updated.

**Comment by bw4sz** [comment]
Looking here at latest pypi release (1.2.0)

https://github.com/weecology/DeepForest/compare/1b53767ca632ae17df44d47a3e84632d62a34922...main

there have been no changes to config.yml, so i'm confused how you don't have the version that matches the repo.

**Comment by ethanwhite** [comment]
@bw4sz - this is for the config in file in `/deepforest/data` see https://github.com/weecology/DeepForest/pull/302#issuecomment-1030333778 (where I made the exact mistake you did.

I just merged @easz's PR so this is fixed now.

Thanks for reporting @saadmazouzi and sorry for the confusion.
