### ISSUE TITLE
remove checkpoint_callback=False to be able to set up checkpointing

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#301]
**Please describe A feature you would like to be added.**

It would be nice to be able to set up [checkpointing](https://pytorch-lightning.readthedocs.io/en/stable/common/weights_loading.html) during training which is not possible in the current deepforest version 1.2.0.

I.e. the following code is not possible with the current deepforest which sets [checkpoint_callback=False](https://github.com/weecology/DeepForest/blob/4f787bed481bc9184937383823e017c0942b4fca/deepforest/main.py#L130) internally.

~~~

callback = ModelCheckpoint(dirpath='temp/dir',
                                 monitor='box_recall', 
                                 mode="max",
                                 save_top_k=3,
                                 filename="box_recall-{epoch:02d}-{box_recall:.2f}")
model.create_trainer(logger=TensorBoardLogger(save_dir='logdir/'), 
                                  callbacks=[callback])
model.trainer.fit(model)

~~~

**Describe the solution you'd like**
remove hard coded `checkpoint_callback=False`

**Describe alternatives you've considered**
-

**Additional context**

~~~
$ conda list | grep torch
pytorch                   1.10.1          py3.9_cuda10.2_cudnn7_0    pytorch
pytorch-lightning         1.5.8              pyhd8ed1ab_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch    
torchaudio                0.10.1               py39_cu102    pytorch    
torchmetrics              0.6.2              pyhd8ed1ab_0    conda-forge
torchvision               0.11.2               py39_cu102    pytorch  
 ~~~

**Comment by bw4sz** [comment]
Thanks for the issue, I agree that this functionality needs to be improved. I think checkpoint callback was deprecated. 

https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#checkpoint-callback

**Comment by bw4sz** [comment]
<img width="1071" alt="Screen Shot 2022-01-31 at 10 54 05 AM" src="https://user-images.githubusercontent.com/1208492/151854902-873028ec-8281-4c41-8151-ada69bbe1328.png">
On second look, it looks like this use case is built in, passing the checkpoint should override 
```
enable_checkpointing = False
```
within the trainer. I think the real issue is that we've got

```
checkpoint_callback = False
```

when we want

```
enable_checkpointing = False
```

I'll make a quick PR.

**Comment by bw4sz** [comment]
Looks like this a recent API change

```
Exception: TypeError: __init__() got an unexpected keyword argument 'enable_checkpointing'
```
I had pytorch-lightning 1.4.1 locally. We made need to pin a version. Hard when these API keep changing.

**Comment by bw4sz** [comment]
```
pip install pytorch-lightning --upgrade
Successfully installed pytorch-lightning-1.5.9 setuptools-59.5.0
```

works.
