### ISSUE TITLE
Saving/loading trained model issue

### ISSUE THREAD

**Issue by liliana175** [weecology/DeepForest#309]
Hi, I'm trying to save and load the model after training but looks like when Ioad it, the config did not change

{'batch_size': 1,
 'distributed_backend': None,
 'gpus': None,
 'nms_thresh': 0.05,
 'score_thresh': 0.1,
 'train': {'csv_file': None,
  'epochs': 1,
  'fast_dev_run': False,
  'lr': 0.001,
  'root_dir': None},
 'validation': {'csv_file': None, 'iou_threshold': 0.4, 'root_dir': None},
 'workers': 1}

I tried to follow your steps in the "getting started" documentation and also the steps of saving the whole model like described in pytorch lightning module and none changes the output

When I upload the model it prints "All keys matched successfully"

I also tried to save it as pth, zip, pl and I'm not able to see changes when loading. Any tip/more description that can help me to properly save and load the model? Thanks in advance

**Comment by easz** [comment]
do you have some code example? how did you train, save and load models?
~~~
config did not change
~~~

The `model.config` is very probably not part of pytorch lightning module and have to be configured manually.

**Comment by bw4sz** [comment]
This is indeed a bug. Good catch @liliana175. If you had changed the .config file on path it would have worked, since we call save_hyperparameters() on deepforest.__init__(). However, since you are probably changing config after init, those changes are not saved. I'm going to see if I can make a quick PR with the following test.

```
from deepforest import main, get_data
import os
from pytorch_lightning import Trainer

m = main.deepforest()
annotations_file = get_data("testfile_deepforest.csv")
print(m.config["train"]["lr"] == 0.2)
#change config
m.config["train"]["lr"] = 0.2
m.config["save-snapshot"] = False
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)

#Create a mock trainer just for testing
trainer = Trainer(fast_dev_run=True)
trainer.fit(m)
m.save_model("saved_model.pl")

new_model = main.deepforest.load_from_checkpoint("saved_model.pl")
assert new_model.config["train"]["lr"] == m.config["train"]["lr"]
``

Which currently fails.

**Comment by bw4sz** [comment]
Looks like this is a function and not a bug. https://pytorch-lightning.readthedocs.io/en/latest/common/hyperparameters.html#save-hyperparameters. If you want to save config, you need to do it from .config.yml and not inline. I will update the docs.
