### ISSUE TITLE
Can not process GeoTIFF

### ISSUE THREAD

**Issue by elock4567** [weecology/DeepForest#311]
**Describe the bug**

Hello, I am trying to process a GeoTIFF using DeepForest and the release model. when I run the package it returns with "no predictions made, returning none" I have adjusted the window size with the same results. when the image is converted to a png it runs smoothly. I need the GeoTIFF to run so I can return shapefiles, to use the bounding boxes for further analysis in GIS software. The sample image I am using is a clip of a larger dataset.
Is there a specific procedure for using GeoTIFFs or a way they need to be formatted?

I did have a tough time installing DeepForest on windows, conda would just hang up and not run, completing the pip install required installing lots of dependencies to be installed separately it may be possible that I missed something? 

**To Reproduce**
```
from deepforest import main
from deepforest import utilities
import os

model = main.deepforest()
model.use_release()
raster= (r"C:\Users\Site3\Site3_rgb_cliped.tiff")
predicted_raster = model.predict_tile(raster, patch_size=400,patch_overlap=0.50, return_plot = True)

```
**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version and environment : 
 - py. 3.9.9
 - DeepForest 1.2.1
 - Imagery: high res 30cm 3 band (originally 4 band) 

**Screenshots**
![image](https://user-images.githubusercontent.com/99748197/154101931-3b45fa83-f3bd-4710-8ecf-6ea6a8377f80.png)

![image](https://user-images.githubusercontent.com/99748197/154102150-4c2e2155-891f-40e6-bc58-c6f77ba69459.png)
Geotiff
**Additional context**
Thank you!

**Comment by easz** [comment]
It should work with geotiff as well. How is your parameter such as `iou_threshold`?

And I will try `patch_size` with `200` on your sample image to see if it works better.

my example:
https://www.kaggle.com/easzil/urban-tree-detection-from-aerial-images

**Comment by bw4sz** [comment]
I don't have any reason to believe that geotif would be different than .png, can you share the geotiff version?

@easz is right, it all depends on patch size, which is a slightly frustrating fact. We are working on it.

```
from deepforest import main
from deepforest.utilities import boxes_to_shapefile
from deepforest.visualize import plot_predictions
import rasterio as rio
from matplotlib import pyplot as plt

m = main.deepforest()
m.use_release()
boxes = m.predict_tile("/Users/benweinstein/Desktop/311_alpha.png",patch_size = 100)
tile = rio.open("/Users/benweinstein/Desktop/311_alpha.png").read()
i = plot_predictions(image=tile, df=boxes)
plt.imshow(i)
```
worked reasonably well, the image is a bit low quality.

![Uploading image.png…]()


I'd guess that patch size of 100 would be more suitable.
