### ISSUE TITLE
Allow users to make a new classification model using existing regression head

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#316]
Followup to convo with @henrykironde  and ansh. 

1. Make a new config argument 'freeze_regression_head' that takes in maybe 'tree' or 'bird', @henrykironde this relates to our discussion that as we have more and more trained models we need a strategy to call them.
2. in deepforest __init__ if config["freeze_regression_head"] is not None, load the particular release model and create a new model with 'classes' argument supplied by the user, but with the existing regression weights.
3. Add a test to test_main.py
4. Add to config documentation and add a small example to the tutorial.
This formalizes the snippet made by @ethanwhite :
https://github.com/weecology/EvergladesSpeciesModel/blob/133a6b2c2d40b425a45b62b41bfb7e40b4f82592/everglades_species.py#L174

**Comment by dassaniansh** [comment]
I'll create a pull request by making a new config argument as mentioned in point 1 and can move forward accordingly.

**Comment by dassaniansh** [comment]
@bw4sz, I opened a pull request as suggested by you earlier, can you please guide me on how to move forward with it?

**Comment by bw4sz** [comment]
@dassaniansh let's keep the convo here. See the link above.

The use_bird_release model has 1 class 'Bird', imagine a user wants to start from that model, but has 5 classes of birds ('flamingo', 'ibis', 'egret','duck', 'goose'). We want them to start from a model that can make predictions of 'birds', but learn new classes.

So in init, we want to load the regression head to the newly created 5 class model. I might also change the name, because its not that we care if the user freezes or not, its that we want them to *start* from the release model for regression weights. Maybe 'start_from_release'? @ethanwhite 

```
model = main.deepforest(num_classes=len(train.label.unique()),label_dict=label_dict)

  # Use the backbone and regression head from the global bird detector to transfer
  # learning about bird detection and bird related features 
      global_bird_detector = main.deepforest()
      global_bird_detector.use_bird_release()
      model.model.backbone.load_state_dict(global_bird_detector.model.backbone.state_dict())
      model.model.head.regression_head.load_state_dict(global_bird_detector.model.head.regression_head.state_dict())
```

**Comment by dassaniansh** [comment]
@bw4sz So what I want to ask here is that do we know how many classes we are going to have right now or do I have to create a single training pipeline that can (will) be trained over all the databases of different classes. Another thing is that hopefully, Should I use the Retinanet model for training purposes or any other? finally, do we have any sample data right now with which I can start the training and testing of the model? What I am thinking right now is that I can start working on an individual retina net model and train it to detect the bird species for now, finalize the model and then include it in the existing pipeline. Please tell me if this will be the correct way to address this issue or not?

**Comment by bw4sz** [comment]
No model training is needed. To create a deepforest model, there is a classes argument.

https://github.com/weecology/DeepForest/blob/02aac1fd8105f18e63c321be170c2c55d82a51c6/deepforest/main.py#L23

so we know at time of model creation how many classes are desired. But there is no reason to start from scratch. So we want to give the user an opportunity to load a baseline model, which has just a single class, and then replace the classification head. The snippet above is all you would need to do as a first step.

**Comment by dassaniansh** [comment]
I have tried to implement what you suggested, can you check whether I was able to understand it properly or not, Thanks.
