### ISSUE TITLE
How to use my own trained model for conducting inference?

### ISSUE THREAD

**Issue by landkwon94** [weecology/DeepForest#324]
Hello Sir, I was previously using the former version of DeepForest which was written 2021 February. But it seems there are some changes in current version.

I want to use my own pre-trained model which has '.h5' file format for my own inference :) 
My original codes written last year are not working properly well now.. So may I ask you the method how to conduct inference with pre-trained model in current version?

Thank you so much!

**Comment by ethanwhite** [comment]
In 2021 June we moved from tensorflow to Pytorch. See #195. Therefore pretained tensorflow models (including those made by the package prior to 2021 June) will no longer work with the current release or main branch.

The tensorflow version of the package as of 2021 June is available in a branch here: https://github.com/weecology/DeepForest/tree/tensorflow

You can try running your old model on that branch, but this version of the code is unmaintained and unsupported. We recommend retraining using the new release if possible.
