### ISSUE TITLE
IoU Evaluation Default Value

### ISSUE THREAD

**Issue by nilsleh** [weecology/DeepForest#332]
**Describe the bug**
The default value of the iou value during evaluation in the [default config file](https://github.com/weecology/DeepForest/blob/main/deepforest/data/deepforest_config.yml) is set to 0.4 and I am wondering why that is the case? The common value in the literature and your [original paper](https://www.mdpi.com/2072-4292/11/11/1309) is 0.5.

**Comment by bw4sz** [comment]
I don't think there is a theoretical justification for any value. It depends on the input resolution of the object and desired bounding box overlap. In the case of trees, you are looking down a three dimensional object that is being represented in a 2D  plane. Given the accuracy of the ground truth and a 4 point nature of the bounding box, I think 0.4 seems reasonable and we've been using this value for a couple years. Its no 'true' than 0.5, also note that IoU is highly sensitive to object size, we even wrote a paper in context of trees:  https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9585420.
I'd recommend choosing a value you feel comfortable with and sticking with it, I don't think this represents something that can be solved.

**Comment by nilsleh** [comment]
Thank you for your reply. I agree that there is no theoretical justification,  but a lower iou threshold will inflate precision and recall scores. So for the sake of model comparison a standardized value should be applied and as far as I can tell that value is 0.5. That was the motivation behind my question.
