### ISSUE TITLE
Model Checkpointing

### ISSUE THREAD

**Issue by nilsleh** [weecology/DeepForest#333]
**Describe the bug**
In [main.py](https://github.com/weecology/DeepForest/blob/02aac1fd8105f18e63c321be170c2c55d82a51c6/deepforest/main.py#L127), the `enable_checkpointing=False` is hard coded. When I pass a lightning ModelCheckpoint to `create_trainer()` then it throws the error:
`Trainer was configured with "enable_checkpointing=False"  but found "ModelCheckpoint" in callback list`.

**To Reproduce**
```
from deepforest import main
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(
        dirpath=ckpt_dir,
        save_top_k=1,
        monitor="box_recall",
        mode="max",
        every_n_epochs=1,
    )
m = main.deepforest()
m.use_release()
m.create_trainer(callbacks = [checkpoint_callback])
m.trainer.fit(m)
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version and environment : venv Python 3.8

**Comment by easz** [comment]
I had the same issue #301.
The fix #304 is not enough.

The hard coded part should be removed (See #298)

**Comment by bw4sz** [comment]
Okay, let's look into this. We want 1) default to be no checkpoint, 2) allow users to add checkpoint. First step is to make a branch with two tests that fail in the current workflow.

**Comment by bw4sz** [comment]
Creating a branch for this issue https://github.com/weecology/DeepForest/tree/model_checkpoint

**Comment by bw4sz** [comment]
Tests pass and merged into main.
