### ISSUE TITLE
Has anyone tried to run Deepforest on Torchserve?

### ISSUE THREAD

**Issue by jeroenVerdonschot** [weecology/DeepForest#334]
I really like Deepforest. It works great and I was wondering if it can run on Torchserve.

It would be great if I could use it together with Torchserve. But I am a newbie on all this stuff and I don't know if it is possible and if so, how to set it up.

I also contacted the Torchserve team to see if they could help me out. (if they do let you know of course).

Thanks, Jeroen

**Comment by bw4sz** [comment]
let me know, what's your serving use case, you want others to upload images to run against the model? Keep me in the loop, i'd be interested in setting something up.

**Comment by jeroenVerdonschot** [comment]
Yes bw4sz,

That's right. I am currently using Deepforest to find trees on the Dutch PDOK aerial imagery:
[https://www.pdok.nl/introductie/-/article/luchtfoto-pdok](url)

I have great results already using the default Deepforest model but I am working on refining the dataset to work even better on the  PDOK dataset in the near future. To do so I need more people to manually help me out. That's why I would like to have the server.

Ideally, I would have a torchvision-PDOK-finetuned-deepforest that everyone who is interested in Dutch trees can use. 😄 

I also asked the guys at Torchserve but no answer yet from them. I'll keep you posted when I receive a response.

Thanks,

Jeroen

**Comment by bw4sz** [comment]
I think torchserve is probably the wrong avenue for this. I think this is the perfect use case for AIDE.

https://github.com/microsoft/aerial_wildlife_detection

You should contact https://twitter.com/b_kellenb who runs that project, he recently told me he has a branch with deepforest already on it. Let me know, this integration has been a long term goal.

**Comment by ethanwhite** [comment]
Closing since this seems to be wrapped up and hasn't been touched in a while. @jeroenVerdonschot - feel free to reopen if useful at some point.
