### ISSUE TITLE
ImportError: cannot import name 'main' from 'deepforest'

### ISSUE THREAD

**Issue by ThomasHaarlem** [weecology/DeepForest#336]
**Describe the bug**
```
Traceback (most recent call last):

  File "C:\Users\Thomas\anaconda3\envs\deepf\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\gisdb\python\pydeepf.py", line 10, in <module>
    from deepforest import main

ImportError: cannot import name 'main' from 'deepforest' (C:\Users\Thomas\anaconda3\envs\deepf\lib\site-packages\deepforest\__init__.py)
```

**To Reproduce**
I've a clean environment 'deepf' in Anaconda for the DeepForest package. I installed Spyder 5.3.0 to run the code in the section ["getting started](https://deepforest.readthedocs.io/en/latest/getting_started.html)" from read the docs.

```
from deepforest import main
from deepforest import get_data
import os
import matplotlib.pyplot as plt
model = main.deepforest()
model.use_release()

img = model.predict_image(path="/Users/benweinstein/Documents/NeonTreeEvaluation/evaluation/RGB/TEAK_049_2019.tif",return_plot=True)

#predict_image returns plot in BlueGreenRed (opencv style), but matplotlib likes RedGreenBlue, switch the channel order.
plt.imshow(img[:,:,::-1])

```

**Environment (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Python version and environment : 3.7, Anaconda1.10.0, Spyder 5.3.0 

**Screenshots**

**Additional context**
* In Anaconda Navigator I added the channel conda-forge in my fresh environment 'deepf' to install DeepForest.
* when I search for "ImportError: cannot import name 'main' from 'deepforest'" I only see results about errors after upgrading PIP. I did not use PIP to install DeepForest.

* I start the script with ```help(modules)``` and I see ```deepforest``` in the list.
* This is the first time I install a task-specific module like DeepForest. So maybe I forgot to change something user-specific in a config-file? Or another really easy step in the process which is obvious for more experienced users? If this is the case, maybe I should have asked for a feature for more installation-guiding. My apologies.

[edit]
* when I carefully follow the path in the error message it says:
```C:\Users\Thomas\anaconda3\envs\deepf\lib\site-packages\deepforest\__init__.py```
but when I follow that path in windows-explorer, I see a difference in the lower or capital `L` in ``` \lib\``` ```C:\Users\Thomas\anaconda3\envs\deepf\Lib\site-packages\deepforest\__init__.py```
Is that something that can lead to the solution? Where and how can I change it?

**Comment by olawale1rty** [comment]
I can not import the main also on Mac M1, getting this error.

`dlopen(/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/lib/python3.10/site-packages/rasterio/_version.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libLerc.4.dylib'
  Referenced from: '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/lib/libgdal.31.dylib'
  Reason: tried: '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/lib/libLerc.4.dylib' (no such file), '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/lib/python3.10/site-packages/rasterio/../../../libLerc.4.dylib' (no such file), '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/lib/python3.10/site-packages/rasterio/../../../libLerc.4.dylib' (no such file), '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/bin/../lib/libLerc.4.dylib' (no such file), '/Users/moshoodmustapha/opt/anaconda3/envs/treecounting/envs/treecounting/bin/../lib/libLerc.4.dylib' (no such file), '/usr/local/lib/libLerc.4.dylib' (no such file), '/usr/lib/libLerc.4.dylib' (no such file)`

**Comment by olawale1rty** [comment]
@ThomasHaarlem Solved by uninstalling and installing rasterio.
