### ISSUE TITLE
Lab Meeting Template

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#36]
Name:

Operating System: OSX 

# Install

Please check off tasks that succeed
- [ ] git clone 
- [ ] conda install
- [ ] Report version
```
(test) MacBook-Pro:DeepForest ben$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepforest
>>> deepforest.__version__
'0.2.3'
```

# Docs

## Landing Page
1. Does the landing page have enough information?
2. Are the python modules reasonably named and laid out?

## Getting Started
- [ ] Predict a single image downloads the prebuilt model and predicts bounding boxes

## Evaluating the prebuilt model
- [ ] Can you run the example and get a similar mAP score (~0.54)

Does the example need more text and explanation?

## Misc

1. What other pages/examples would be useful?

2. Do the future warnings from numpy or tensorflow bother you? They could be suppressed.

3. *Experimental* PyPI install (dev branch)

Deactivate the conda env and move out of the repo

```
virtualenv -p python3 test

source test/bin/activate
pip install DeepForest
pip install git+git://github.com/bw4sz/keras-retinanet.git
python
(test) MacBook-Pro:Desktop ben$ python
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepforest
>>> deepforest.__version__
'0.2.4'
```

**Comment by diazrenata** [comment]
> Name:
> 
> Operating System: OSX
> # Install
> 
> Please check off tasks that succeed
> 
>     * [ ]  git clone
> 
>     * [ ]  conda install
> 
>     * [ ]  Report version
> 
> 
> ```
> (test) MacBook-Pro:DeepForest ben$ python
> Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import deepforest
> >>> deepforest.__version__
> '0.2.3'
> ```
> 
> # Docs
> ## Landing Page
> 
>     1. Does the landing page have enough information?
> 
>     2. Are the python modules reasonably named and laid out?
> 
> 
> ## Getting Started
> 
>     * [ ]  Predict a single image downloads the prebuilt model and predicts bounding boxes
> 
> 
> ## Evaluating the prebuilt model
> 
>     * [ ]  Can you run the example and get a similar mAP score (~0.54)
> 
> 
> Does the example need more text and explanation?
> ## Misc
> 
>     1. What other pages/examples would be useful?
> 
>     2. Do the future warnings from numpy or tensorflow bother you? They could be suppressed.
> 
>     3. _Experimental_ PyPI install (dev branch)
> 
> 
> Deactivate the conda env and move out of the repo
> 
> ```
> virtualenv -p python3 test
> 
> source test/bin/activate
> pip install DeepForest
> pip install git+git://github.com/bw4sz/keras-retinanet.git
> python
> (test) MacBook-Pro:Desktop ben$ python
> Python 3.7.0 (default, Jul 23 2018, 20:22:55)
> [Clang 9.1.0 (clang-902.0.39.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import deepforest
> >>> deepforest.__version__
> '0.2.4'
> ```

**Comment by bw4sz** [comment]
Thanks @diazrenata, those aren't errors, but warnings from other libraries. I mentioned I could suppress them, they have nothing to do with DeepForest. So to do on my end is warn the user that it can be ignored.

**Comment by ha0ye** [comment]
Name: Hao Ye

Operating System: OS X 10.13.6

# Install
Please check off tasks that succeed

- [x] git clone
- [x] conda install
- [x] Report version
```
(DeepForest) [15:13:26] hye@shirasagi:~/projects/DeepForest > python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepforest
>>> deepforest.__version__
'0.2.3'
```

# Docs
## Landing Page
1. Does the landing page have enough information?
2. Are the python modules reasonably named and laid out?
## Getting Started
- [ ] Predict a single image downloads the prebuilt model and predicts bounding boxes
## Evaluating the prebuilt model
- [ ] Can you run the example and get a similar mAP score (~0.54)
```
>>> from deepforest import deepforest
>>> from deepforest import get_data
>>> 
>>> test_model = deepforest.deepforest()
Reading config file: deepforest_config.yml
No model initialized, either train or load an existing retinanet model
>>> test_model.use_release()
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/v0.2.1 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/v0.2.1
tracking <tf.Variable 'Variable_10:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_11:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_12:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_13:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_14:0' shape=(9, 4) dtype=float32> anchors
>>> 
>>> annotations_file = get_data("testfile_deepforest.csv")
>>> mAP = test_model.evaluate_generator(annotations=annotations_file)
There are 1 unique labels: ['Tree'] 
Disabling snapshot saving
Running network: 100% (1 of 1) |#########| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (1 of 1) |#####| Elapsed Time: 0:00:00 Time:  0:00:00
61 instances of class Tree with average precision: 0.6777
mAP using the weighted average of precisions among classes: 0.6777
mAP: 0.6777
>>> print("Mean Average Precision is: {:.3f}".format(mAP))
Mean Average Precision is: 0.678
```
Does the example need more text and explanation?

## Misc
1. What other pages/examples would be useful?
2. Do the future warnings from numpy or tensorflow bother you? They could be suppressed.
3. Experimental PyPI install (dev branch)

**Comment by gmyenni** [comment]
Name: Glenda

Operating System: OSX 10.14.6 

Install

- [ ] git clone

- [ ]  conda install

- [ ]  Report version

Getting Started

- [ ]  Predict a single image downloads the prebuilt model and predicts bounding boxes

Evaluating the prebuilt model

- [ ]  Can you run the example and get a similar mAP score (~0.54)

**Comment by diazrenata** [comment]
@bw4sz :100:! I've literally never used any of these packages, so have no frame of reference for what is normal and what is a sign that I've got it set up wrong. I imagine your intended users have a little more exposure and might not be fazed by them....
