### ISSUE TITLE
Shapefile_to_annotations from example not working as 'box_points' and 'buffer_size' args. aren't defined in repo. 

### ISSUE THREAD

**Issue by j-la-haye** [weecology/DeepForest#361]
**Describe the bug**
shapefile_to_annotations shown on bird_detector example does not have the shown arguments: 'box_points' and 'buffer_size'

Does the method just need to updated on the Git repo?

**To Reproduce**
df = shapefile_to_annotations(
    shapefile="annotations.shp", 
    rgb="image_path", box_points=True, buffer_size=0.15
)

The call fails because deepforest.utilities.shapefile_to_annotations does not have the 'box_points' and 'buffer_size' args. defined. 

**Environment (please complete the following information):**
 - OS: Mac Osx
 - Python version and environment : 3.9

**Screenshots**

**Additional context**

**Comment by bw4sz** [comment]
```
pip install --update deepforest
```

I'm 99% sure that you are just a version behind.

**Comment by bw4sz** [comment]
update here?

**Comment by j-la-haye** [comment]
@bw4sz I ran pip install --upgrade deepforest and do not see any changes in utilities.shapefile_to_annotations

Something else I should try or look elsewhere?

Thanks!

![Screenshot from 2022-11-04 10-54-48](https://user-images.githubusercontent.com/26750133/199945069-b5b7f3f2-aefd-4eb6-8a34-720a5514c5b6.png)

**Comment by ethanwhite** [comment]
@j-la-haye - I think the docs are just wrong. Assuming you have a shapefile of bounding boxes can you remove the `box_points=True, buffer_size=0.15` arguments and see if everything works.

**Comment by bw4sz** [comment]
I completely misunderstood this issue. Yes, the docs are wrong.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/1208492/200419142-36ccbf37-a1a4-490c-a3ae-3415a79bb5ba.png">

I have figured out what happened, this doc was pointing at the bird_detector preprocessing function with the same name that lived outside deepforest here: https://github.com/weecology/BirdDetector/blob/616bfa18775317288d7155e54243a302ce9a5fd4/utils/preprocess.py#L36

I actually think is a super useful function and i'm writing a test and will add in into the deepforest.shapefile_to_annotations function.

**Comment by j-la-haye** [comment]
@bw4sz thanks very much for your prompt response!
