### ISSUE TITLE
Add examples of projects using DeepForest to the README

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#362]
* https://ieeexplore.ieee.org/abstract/document/9911397
* https://www.arcgis.com/home/item.html?id=4af356858b1044908d9204f8b79ced99
* https://agisoft.freshdesk.com/support/solutions/articles/31000162552-automatic-detection-of-objects-on-orthomosaic
* https://doi.org/10.3390/rs14194963
* https://arxiv.org/pdf/2201.11192.pdf

**Comment by bw4sz** [comment]
https://arxiv.org/pdf/2201.11192.pdf

**Comment by ethanwhite** [comment]
Added to the docs in 584eb0c3bb9c44416bf96be5c3abc248e6a919fd
