### ISSUE TITLE
Crop size question

### ISSUE THREAD

**Issue by aleksandraradecka1** [weecology/DeepForest#371]
Hello, 

I am experimenting with DeepForest package (BTW it is great, thanks!) and I am not sure which crop sizes should I try (I do not fully understand the relation between the resolution, crop size and focal view). 

My data is 0.1 m as well, but my research objects are probably a lot smaller than NEON's - 1-3 m in diameter (secondary succession). My crops are 416x416. In fact they are originally either 208x208 or 104x104, but upsampled to 416x416 (long story why). 

Could you please advise/explain:
1. Should I make my crops smaller to make the relation crops size - object size similar to DeepForest's or it would probably be better if I leave the crop size similar to your 400x400?
2. What, from your experience, would be better - to have crops of different sizes or have crops upsampled/downsampled to the same size?
3. What exactly happens with the crops we give to make them suitable for RetinaNet architecture?

I would be very greatful for the help. 
All best best, 
Aleksandra

**Comment by bw4sz** [comment]
Hi Aleksandra, 

You are not alone, there is not an equation that I know of that relates to object size, the focal view and the trained model weights. Its very high on my list for research. Trial and error is the only solution at the moment. Can you show me a sample image and some sample predictions and we can work through it together? Retinanet does resize them, upstream of DeepForest, from 

https://pytorch.org/vision/0.12/_modules/torchvision/models/detection/retinanet.html
```
        min_size (int): minimum size of the image to be rescaled before feeding it to the backbone
        max_size (int): maximum size of the image to be rescaled before feeding it to the backbone
```

But the anchor box generator creates a variety of anchor sizes that are used as object proposals. If you have large tiles, the 

predict_tile function has a patch_size argument that is very useful. 

See https://deepforest.readthedocs.io/en/latest/better.html

**Comment by ethanwhite** [comment]
Closing since this is all wrapped up. @aleksandraradecka1 -  you're more than welcome to reopen if you have more questions or feedback
