### ISSUE TITLE
possible error? on conda install

### ISSUE THREAD

**Issue by ha0ye** [weecology/DeepForest#38]
on conda 4.6.2, python 3.6.9, OS X 10.13.6
```
Successfully built keras-resnet keras-retinanet psutil wrapt termcolor gast absl-py
ERROR: keras-retinanet 0.5.1 has requirement keras-resnet==0.1.0, but you'll have keras-resnet 0.2.0 which is incompatible.
```

**Comment by MarconiS** [comment]
installing 4.7.12 works to me (macOS 10.15.1)

**Comment by bw4sz** [comment]
Trying to determine if this is a conda version issue. Works on
```
(DeepForest_dask) MacBook-Pro:DeepForest ben$ conda --version
conda 4.7.12
```

will install 4.6.2 to check.

**Comment by bw4sz** [comment]
adding to FAQ for the moment.

**Comment by bw4sz** [comment]
Considering this closed until I can reproduce on travis or locally. Added better error handling to help users, but I'm going to guess this will reappear, hopefully as we come to a stable install I can find which dep is the key.
