### ISSUE TITLE
Demo  does not work

### ISSUE THREAD

**Issue by aloboa** [weecology/DeepForest#386]
**Describe the bug**
Demo  does not work
**To Reproduce**
Just click on 
http://weecology.westus.cloudapp.azure.com/neon/
Results on:
Unable to connect
Firefox can’t establish a connection to the server at weecology.westus.cloudapp.azure.com.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by ethanwhite** [comment]
Thanks for the report @aloboa. We are in the process of moving that site off of Azure and onto a different server, but it's taking a little longer than expected.

For now, we should probably change that link to https://visualize.idtrees.org/ and I'd welcome a PR if you have a few minutes.

**Comment by aloboa** [comment]
Not sure I understand. I was expecting a link to a demo of running the package, while https://visualize.idtrees.org/ is rather a demo of results. But, considering the material in https://deepforest.readthedocs.io/en/latest/, the demo I thought I could find in the reported weecology link might be unnecessary.

**Comment by ethanwhite** [comment]
The site that was present at http://weecology.westus.cloudapp.azure.com/neon/ allowed you to upload an image and run the model on it, so it was more of a demo as you describe, but not one that showed the commands you would run to do things yourself. A couple of months ago @bw4sz & @henrykironde were working on moving that site over to a new server, but I don't think that work was ever completed.

Given the way you were viewing what link provided do you think linking to https://deepforest.readthedocs.io/en/latest/getting_started.html make more sense?

Alternatively we can just get rid of the link and put it back if/when that site transfer is actually complete.

**Comment by aloboa** [comment]
> The site that was present at http://weecology.westus.cloudapp.azure.com/neon/ allowed you to upload an image and run the model on it, so it was more of a demo as you describe, but not one that showed the commands you would run to do things yourself. 

Actually, that would be cool. Obviously running commands would be even better, but I understand more involved.
Linking to https://visualize.idtrees.org/  somewhere is obviously useful, but not there.
