### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#39]
Will make install easier for most data science focused Python users. @henrykironde can help walk you through the process of doing this if helpful.

**Comment by bw4sz** [comment]
@henrykironde do you know how conda forge handles c++ builds for windows? I have a user 

https://github.com/weecology/DeepForest/issues/56

reporting pain points in building the C++ for the keras-retinanet fork.

```
pip install git+git://github.com/bw4sz/keras-retinanet.git
```
Would conda forge help here? Something like create a windows instance on azure, build the library and make a wheel? Do you have any experience in this? After the holiday lets brainstorm on how to make this easier.

**Comment by bw4sz** [comment]
@henrykironde the new installation process is complete, so the next step is conda forge. @ethanwhite  thought you can help here.

**Comment by ethanwhite** [comment]
Hey @henrykironde - we can chat some more about this in our planning meeting on Monday, but I thought this was a case where your expertise could contribute a lot to this project by getting it up and running on conda-forge. @bw4sz's now done a bunch of work to get everything working smoothly on pypi and so things are probably in good shape to explore getting up and running on conda.

**Comment by bw4sz** [comment]
Can this be closed?

**Comment by bw4sz** [comment]
Closed except for windows, let's move any additional conversation to feedstock repo.
