### ISSUE TITLE
Can you do it locally in Python?

### ISSUE THREAD

**Issue by stphtan94117** [weecology/DeepForest#390]
Colab's network is not friendly to me, so can you make python(.py) on computer?
can you make a train and predict.py locally?
thanks

**Comment by ethanwhite** [comment]
Yes, this is a regular Python package that works locally. The colab is just designed to let people experiment without having to do a local install.

Instructions on installing are here: https://deepforest.readthedocs.io/en/latest/installation.html

Once you've installed the package I recommend checking out the [Getting Started Guide](https://deepforest.readthedocs.io/en/latest/getting_started.html)

**Comment by stphtan94117** [comment]
> Yes, this is a regular Python package that works locally. The colab is just designed to let people experiment without having to do a local install.
> 
> Instructions on installing are here: https://deepforest.readthedocs.io/en/latest/installation.html
> 
> Once you've installed the package I recommend checking out the [Getting Started Guide](https://deepforest.readthedocs.io/en/latest/getting_started.html)

Sorry, I am a beginner in python, I don’t understand the code very well, can you make a simple train.py, thank you

**Comment by ethanwhite** [comment]
The docs walk you through the basic steps of using the software including training your own models. Check out the [Getting Started page](https://deepforest.readthedocs.io/en/latest/getting_started.html) which includes some video tutorials. You are welcome to ask questions if you have them along the way.
