### ISSUE TITLE
Remove .to(CUDA) statements to improve speed and unify with pytorch lightning framework.

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#407]
DeepForest is a pytorch lightning module. It therefore knows what device it is on, it should not need to be copied to GPU. 

https://lightning.ai/docs/pytorch/stable/starter/converting.html#remove-any-cuda-or-to-device-calls

This appears in all the predict statements

https://github.com/weecology/DeepForest/blob/8e91b0ae8c6296cc9d62dd229335b04fd29ca7c9/deepforest/main.py#L264

More broadly, the predict statements should use trainer arguments and follow the pytorch lightning API. We are currently flirting with proper usage, but manually moving data around. We should make better use of dataloaders and trainer.predict where possible. This would be a good goal for DeepForest 1.3

**Comment by bw4sz** [comment]
There is reason to believe this is a non trivial time at scale in deepforest.main.init()

<img width="1818" alt="image" src="https://user-images.githubusercontent.com/1208492/226701752-bc6ae6da-3391-4f71-bbb2-557ac6a8a7c5.png">

**Comment by Pranav-Saxena** [comment]
Hi @bw4sz . I have fixed this issue in PR #417 . Can you please review it and merge it if it's fine

**Comment by ethanwhite** [comment]
@Pranav-Saxena see my note in #417

**Comment by ethanwhite** [comment]
@bw4sz I think you finished this in #410 if I'm understanding things correctly in which case this could be closed.
