### ISSUE TITLE
Use pip's system for non-pypi dependencies

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#41]
This should allow the fork of `keras-retinanet` to be seamlessly installed without the second step: https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi

**Comment by bw4sz** [comment]
yes, i tried that for a couple hours. It seems 

https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repo-as-a-dependency

that having direct links is seen as a security risk. test.pypi rejected it. I'll document it here and try again.

**Comment by bw4sz** [comment]
Trumped by pypi installed, wrapped a static version of retinanet, see #60
