### ISSUE TITLE
Interpret the result of multclass model

### ISSUE THREAD

**Issue by NickHarnau** [weecology/DeepForest#441]
Hey, 
I am training a multiclass modell. 
When I evaluate this I am getting 
1. Results
2. Box_preciscion 
3. Box_recall
4.  class_recall 
    i. label 
    ii recall
    iii precision 
    iv size 

So this is how expetcted. But how do I interpretate this? 
I am following the way with a backbone model and then extend this.
In the original way the documentation says: 
'box precision is the proportion of predicted boxes which overlap a ground truth box.'
'The recall is the proportion of ground truth which have a true positive match with a prediction...' 

How is this in a multiclass model? Does those values have the same meaning? 
And if yes, is the recall and precision than based on the predicted boxes or based on the original dataset 
(I mean if the original dataset has 1000 boxes, but the backbone model predictes only 500 boxes-> is the recall and precision than based on those 1000 boxes or based on the 500 boxes?) 

I hope you understand my point. Thanks in advance!

**Comment by NickHarnau** [comment]
So I have just checked the code and I think there is a logical mistake. 

So in the evaluate.evaluate function we calculate the box_precision and box_recall based on the IoU Threshold. The seems logical since we want to check if the BBoxes were correct. 
Inside the evaluate.evaluate the class recall ist calculatetd. This is done by calling the compute_class_recall function with results as parameter. results is a DF that contains all predictions, true labels, and if there is a match. The match column is 1 when the IoU is over the IoU Threshold. So the results DF contains data, where the IoU is > and < than the threshold. 
Based on this the class_recall is calculated For each group we caluclate this. For Example the Recall is calculated with the sum of where true_label == predicted label divided by the len of this group DF. 

But I think there is the logical mistake. In the results DF are all predictions include. But this doesn't make sense. Since we say when the IoU is > IoU Threshold the box is predicted correct. So the precison and recall for a class should be based on this. 
In my opinion we need in the compute_class_recall something like this: 

    for name, group in box_results.groupby("true_label"):
        correct_predicted_bboxes = group.loc[group['match']==1]
        class_recall_dict[name] = sum( correct_predicted_bboxes.true_label ==  correct_predicted_bboxes.predicted_label)/group.shape[0]
        number_of_predictions = box_results[box_results.predicted_label==name].shape[0]
        if number_of_predictions == 0:
            class_precision_dict[name] = 0
        else:
            class_precision_dict[name] = sum( correct_predicted_bboxes.true_label ==  correct_predicted_bboxes.predicted_label)/number_of_predictions
        class_size[name] = group.shape[0]

**Comment by bw4sz** [comment]
Hi @NickHarnau thanks for the thoughts. I've read this a few times and I confess I cannot understand what you are trying to explain. Let's worth through this more slowly. Can you show me an example with a evaluate score, and then the eval score you think is correct? There is too much here to try to unpack. One aspect that may help that I've gone back and forth on is whether the class recall should include boxes that were missed. So let's say you have 5 trees, with a true state of 2 maples and 3 oaks. The model predicts four trees, with 3 oaks and 1 maple. What is the correct 'class recall'. The code is currently structured to have a 4/5 box_recall and then 3/3 oaks and 1/1 maple. So the class recall is 100%. Its a very literal interpretation of recall. The model made 4 class predictions and all are accurate. This is the inherent challenge in multi-task models like retinanet. As long as you are consistent, i'm not sure either way is more correct.

**Comment by NickHarnau** [comment]
Hi @bw4sz  thanks for your reply! 
I am trying to explain it with an example :) 

What do you mean by prediction in your answer? I would interprate this as TP boxes after the IoU threshold.
As far as I understand the Framwork, there are two kinds of predictions. 
1. The prediciton of the model based on the score parameter (default = 0.1) 
2. The TP predictions based on the IoU threshold (default = 0.4) 

As far as I understood it: 
we have 5 trees. 3 oaks and 2 maples. The model makes a preditcion with 8 trees - 4 oaks and 4 maples. After looking at the IoU threshold we get 4 tree predictions - 3 oaks and 1 maple. 
So by looking at the code the box_recall is 4/5 and the box_precision is 4/8.
So you the calculating the class_recall based on the second predictions (after IoU threshold). 
That makes totally sense for me, but that is not how it is implemented in the code I guess.


But let us look at my example with slightly different numbers and bit more complex:

So first some statements: 
Recall = Correctly Identified Object (TP) / all truth Objects (TP+FN)
Precision = Correctly Identified Object (TP) / all predictions of class (TP+FP)



I am unsure about the code. I am especially looking at the evaluate.evaluate and evaluate.compute_class_recall function. 

Let's start with the evaluate.evaluate function:
This function takes an argument the predictions and ground truth data. Lets say our ground truth data contains 10 trees - 5 maples and 5 oaks. The _prediction_ dataframe contains 12 predictions (e.g. Score>0.1) with 8 maples and 4 oaks. From those two we are getting a _result_ dataframe. This dataframe contains always as many rows as our ground truth dataframe. In this dataframe we have the IoU and the predicted and true label. From this _result_ dataframe the Box_Precision and Box_Recall is calculated. For that we set an IoU Threshold. All Predictions over this Threshold (e.g.0.4)  are considered to be true positive . Let us say in our case this are the case for TP= 9 -> Prediction: 6 maples and 3 oaks, Truth: 5 maples and 4 oaks. FN=1, FP = 3
From that we get the Box_Precision of 9/12 and Box_Recall of 9/10. 
So far so good!
So in the next step the compute_class_recall function is called for calculating the class_recall and class_precision. The compute_class_recall function takes the results dataframe as argument. Like mentioned, the results dataframe has the same length as the ground truth dataframe and is the base for calculating the TP. 
So and at this point I am getting the confused. 

**In the code:** 
The compute_class_recall takes here the _results_ dataframe as an argument. The _results_ dataframe is at this point as long as our ground truth dataframe (leaving out that the predicted_label=na rows where dropped). This _results_ dataframe is now the base for calculating the class precision and class recall. **We are not first check our predictions for the TP. The IoU Threshold does not play a role for calculating the class_recall and class_precision. Neither does the _predictions_ dataframe**. So considering the code, 
TP_M = 5 / FP_M = 1 /  FN_M = 0 /  TP_O = 3 /  FP_O = 0 / FN_O = 2
maple_recall =  1 / maple_precision = 5/6  / oaks_recall= 3/5 / oaks_precision=1 
This is the how the code implementation is right now

**logical**
The two options from the beginning: 

**1.** 
The compute_class_recall takes here the results dataframe as an argument. The results dataframe is at this point as long as our ground truth dataframe. This results dataframe is now the base for calculating the class precision and class recall. In the result dataframe we take the **IoU threshold to identify TP boxes**. This is the base  calculating the class_recall and class_precision. 
TP_M = 5 / FP_M = 1 /  FN_M = 0 /  TP_O = 3 /  FP_O = 0 / FN_O = 2
So maple_recall =  1 / maple_precision = 5/6  / oaks_recall= 3/4 / oaks_precision=1. 
So the oaks_recall here is different, because we take the TP boxes as references (the true classes in contrast to the predicted classes of the TP boxes). The interpretation is like follow: 
From the boxes correctly predicted by the model, 3/4 of all oaks are found.
---> This is what you claimed how the class_recall is calculated in your reply. 

**2** 
Modify the  compute_class_recall to take the _results_ dataframe and the _prediction_ dataframe as arguments. Those dataframes are now the base for calculating the class_recall and class_precision.  In the result dataframe we take the **IoU threshold to identify TP boxes**. But now the TP boxes are not our reference. The ground_truth dataframe is our reference.
TP_M = 5 / FP_M = 3 /  FN_M = 0 /  TP_O = 3 /  FP_O = 1 / FN_O = 2
So maple_recall =  1 / maple_precision = 5/8  / oaks_recall= 3/5 / oaks_precision=3/4.
So there are different values here is different, because we take the truth data and predictions as references (the true classes in contrast to the predicted classes of the ground truth dataframe ). The interpretation is like follow: 
The model finds 3/5 of all oaks. 



I mean let's step back -> how you claimed it depends on the intepretation and if it is consistent --> so wether using **1. or 2.** does not matter. But what matters is that both approaches are not found in the code. The approach in the code does not take into account at all the IoU Threshold for calculating the class_recall and class_precision. 


Maybe I have a mistake in my thinking or I am having an older Version of the code. (I used pip install, so I should have the latest version). Do I miss something? 
I already did some modification in the code in the evaluate.evaluate and evaluate.compute_class_recall -> so if you are interested I can provide it or we can use it for further discussion :) 

I am more than happy for your Feedback! I hope that my example makes sense :)

**Comment by bw4sz** [comment]
It took me awhile to understand your example, but I do think you are correct. The crux is that the class recall was including all predictions, not just the matched ones. That was an error. Pull request is above and should be merged shortly.
