### ISSUE TITLE
Potential ReferenceError in predict_tile

### ISSUE THREAD

**Issue by stilkin-pxl** [weecology/DeepForest#443]
**Describe the bug**
When predicting multiple tiles sequentially, 
several of them (about a quarter) produce the following error:
`ReferenceError: weakly-referenced object no longer exists`

This problem seems to originate from _inside_ the Deepforest Library on the following location:
```
  File "/home/research/.local/lib/python3.10/site-packages/deepforest/main.py", line 448, in predict_tile
    batched_results = self.trainer.predict(self, self.predict_dataloader(ds))
```

**To Reproduce**
_Steps to reproduce the behavior:_
Sequentially call `model.predict_tile()` several times (in my case 18 times) 

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - Python version and environment: 3.10

**Additional context**
_Add any other context about the problem here._
I am exposing DeepForest as a web service using **Flask**, 
running on a workstation with a graphics card so I can use it on a laptop without a graphics card.

This problem did not appear to occur several weeks prior to today, 
but I have updated several packages on my workstation since. 
I unfortunately did not document which version of DeepForest / Python I was running before this problem started appearing.

Code snippet in my own code where this problem occurs:
```
def get_tree_rects(file_name, patch_size=900, overlap=0.4, thresh=0.5):
    model = main.deepforest()
    model.use_release()
    model.config["score_thresh"] = thresh
    Image.MAX_IMAGE_PIXELS = None

    tree_predictions = model.predict_tile(file_name, return_plot=False, patch_size=patch_size, patch_overlap=overlap)
    print(tree_predictions)
    return tree_predictions
```

Does anyone have an idea where I could start to fix this issue?
The stack trace seems to point to a section of the library itself, so I would like to make sure that the problem is not there but somewhere in a part of my own code (where I can change or fix it).

Thanks in advance!

**Comment by ethanwhite** [comment]
See if the FAQ on this helps: https://deepforest.readthedocs.io/en/latest/FAQ.html#weakly-referenced-objects

If not let us know and we can continue the conversation.

**Comment by stilkin-pxl** [comment]
Hi @ethanwhite , thank you for your quick response!

Unfortunately, the link did not provide a solution to the weak reference problem I am currently struggling with.

Saving and restoring the model from disk does appear to reduce the load time, so in a pinch I could just reload the model and redo the work that fails due to the ReferenceError. I am not hugely fond of this approach however, so if you have any other avenues I could pursue, that would be very welcome.

Best regards

**Comment by ethanwhite** [comment]
I've also tried the version with the model creation and prediction inside a function and can't reproduce locally:

```python
from deepforest import main
from deepforest import get_data


def predict_me(raster_path):
    model = main.deepforest()
    model.use_release()
    model.config["num_workers"] = 4
    prediction = model.predict_tile(raster_path, patch_size=300,patch_overlap=0.25)
    return prediction

raster_path = get_data("OSBS_029.tif")
predicted_rasters = [predict_me(raster_path) for i in range(0,20)]
```

@stilkin-pxl - once if you can get a reprex to reproduce on your system let me know and then we'll go from there.

**Comment by bw4sz** [comment]
I believe this happens because garbage collect deletes the reference to deepforest.trainer object. If you are looping through a set of tiles and calling predict, you can try creating the trainer object within the loop. 

```
for x in tiles_to_predict:
    m.create_trainer()
    m.predict_tile(x)
```

Let me know if that solves the issue. This upstream of us, but in most cases creating the trainer is not expensive. I will add to docs if this solves it.

**Comment by stilkin-pxl** [comment]
> 

I can reproduce it with the first example, it fails in the 7th loop out of 20.
I attached the output of the run to this post:
[output_log.txt](https://github.com/weecology/DeepForest/files/11439874/output_log.txt)

This makes me think there might be something wrong with my setup 🤔 
Ubuntu 22.04.2 LTS, Python 3.10.6, 
but based on the output I may be using DeepForest 1.0.0 (can you confirm this?)

**Comment by stilkin-pxl** [comment]
I can also reproduce it with the second example, it fails in the second loop (I tried this multiple times to confirm).

I attached the output of the run to this post:
[output_log2.txt](https://github.com/weecology/DeepForest/files/11441475/output_log2.txt)


I'm not sure if that's important here, but I also want to mention that I am loading from a plain image file (PNG or JPEG, not a tiff)

**Comment by ethanwhite** [comment]
@stilkin-pxl - that 1.0.0 is the model not the software version (which is definitely confusing and we're working on it).

1\. Do you get the same result with the `raster_path = get_data("OSBS_029.tif")` in my reprex as with `example2.jpg`? If not, can you share `example2.jpg` with us (privately over email is fine if you don't want to post it).

2\. Can you check the deepforest version with:

```python
import deepforest
deepforest.__version__
```

If it's not 1.2.7 can you upgrade using `pip`.

3\. Does @bw4sz's suggestion fix things. Here's a reprex for it:

```python
from deepforest import main
from deepforest import get_data

model = main.deepforest()
model.use_release()

raster_path = get_data("OSBS_029.tif")

predicted_rasters = []
for i in range(0, 20):
    model.create_trainer()
    predicted_rasters[i] = model.predict_tile(raster_path, patch_size=300,patch_overlap=0.25)
```

4\. If you get the same result when doing (1) using DeepForest 1.2.7 and (3) doesn't fix things then we'll need versions of all of the Python packages involved to go any further (`pip list` or `conda list` should do the trick).

**Comment by ethanwhite** [comment]
> I'm not sure if that's important here, but I also want to mention that I am loading from a plain image file (PNG or JPEG, not a tiff)

It's a good idea, but I thought of the same thing and also tested with .png by swapping out `raster_path = get_data("OSBS_029.tif")` for `raster_path = get_data("OSBS_029.png")`.

**Comment by bw4sz** [comment]
Great, adding to docs.

**Comment by ethanwhite** [comment]
@stilkin-pxl - nothing to apologize for. Glad we got it figured out. The inconsistency of this error has made it hard to deal with in the past and we're always glad to sort out another example to make it easier for folks going forward. Hopefully at some point the upstream computer vision packages will get it sorted out, but for now this sort of reporting and research is exactly what we need. Much appreciated.
