### ISSUE TITLE
Validation not starting

### ISSUE THREAD

**Issue by rickyprasojo** [weecology/DeepForest#451]
Hello i got some issue here. So when i run my model it only running on training, but the validation wont run. There is validation bar but it wont run. Anyone know how to fix this?

**Comment by ethanwhite** [comment]
Hi @rickyprasojo. We'll need your help to understand what isn't working for you. At the most basic level you can describe the commands you ran and what you saw as the result. The best way to do this is to produce a simple reproducible example. I'll show you an example of this. To get this I walked through the [Evaluation page in the docs](https://deepforest.readthedocs.io/en/latest/Evaluation.html) and got the relevant pieces.

```python
from deepforest import evaluate
from deepforest import main
from deepforest import get_data
import os
import pandas as pd

m = main.deepforest()
m.use_release()

csv_file = get_data("OSBS_029.csv")
data_dir = os.path.dirname(csv_file)
ground_truth = pd.read_csv(csv_file)

predictions = m.predict_file(csv_file=csv_file, root_dir=data_dir)
result = evaluate.evaluate(predictions=predictions, ground_df=ground_truth, root_dir=data_dir)
```

Does this code produce the problem you were seeing? If not, can you change it to more closely match your example until you get the same behavior?
