### ISSUE TITLE
Shapefile to annotations format bug

### ISSUE THREAD

**Issue by antoniosilva9116** [weecology/DeepForest#465]
**Describe the bug**
Hi! I used the code to convert the shapefile with annotations that I think you are authors (https://zenodo.org/record/4047083). I imported in a jupyter notebook with Deepforest last release (that runs everything well to convert XML to annotations) but when I try to reproduce the notebook here (https://github.com/weecology/DeepForest_demos/blob/master/street_tree/StreetTrees.ipynb) that I think are the same shapefile annotations I receive the following output (I put a print of result variable in line 326 in file https://github.com/weecology/DeepForest/blob/main/deepforest/utilities.py):

```
image_path    xmin     ymin    xmax     ymax label
0     street_trees_train.tif -761348  1382905 -761348  1382905  Tree 
(...)
1032  street_trees_train.tif -761348  1382905 -761348  1382905  Tree
```

that will correspond to a empty data frame.

If I set the convert_to_boxes parameter to True, I receive the following error:

```
ValueError: x attribute access only provided for Point geometries
(...)
273         for x, y in zip(gdf.geometry.x.astype(float), gdf.geometry.y.astype(float))
```

**To Reproduce**
Install last version of DeepForest and run shapefile_to_annotations function using train.shp and street_trees_train.tif files provide in the link: https://zenodo.org/record/4047083

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version and environment: 3.10

**Comment by antoniosilva9116** [comment]
@bw4sz, thank you for your answer. I'm testing the shapefile_to_annotations function to figure out what's wrong. The problem can be the update in geopandas and rasterio libraries. I found that `geopandas.bounds` gives columns minx, miny, maxx, maxy values containing the bounds for each geometry. This can probably update the following lines:
```
    if convert_to_boxes:
        gdf["geometry"] = [
            shapely.geometry.Point(x, y)
            for x, y in zip(gdf.geometry.x.astype(float), gdf.geometry.y.astype(float))
        ]
        gdf["geometry"] = [
            shapely.geometry.box(left, bottom, right, top)
            for left, bottom, right, top in gdf.geometry.buffer(buffer_size).bounds.values
        ]
```
However, the error is the same. When transforming project coordinates into image coordinates the 
output is as follows:

```
image_path    xmin     ymin    xmax     ymax label
0     street_trees_train.tif -761348  1382905 -761348  1382905  Tree
(...)
1032  street_trees_train.tif -761348  1382905 -761348  1382905  Tree
```

I put a print line of image bounds and resolutions and received the following output:

```
[INFO] image bounds (left, bottom, right, top): (761226.0, 1381154.0, 762590.0, 1382951.0)
[INFO] image resolution (x_resolution, y_resolution): (1.0, 1.0)
```

I hope that we can figure out what is wrong

**Comment by bw4sz** [comment]
Okay, i'm understanding now. Those demos have not been updated in 4 years. I'll make an issue, but we want in DeepForest 2.0 to have demos much closer integrated. The function you are looking at has been superceded. Are you just hoping to run this particular demo?

**Comment by bw4sz** [comment]
I added deprecation notice to the old repo. @antoniosilva9116 let's close this, but open a discussion on how we can help you get started with the package.
