### ISSUE TITLE
How can I restore and use a trained and saved model?

### ISSUE THREAD

**Issue by Caio-Giulio-Cesare** [weecology/DeepForest#470]
HI everyone.
I trained e model and saved it by the command

model.create_trainer()
model.trainer.fit(model)

model.save_model("mymodel_1.pt")

And the model was saved in the file "mymodel_1.pt"

I would like, during anoter execution of the program, use this saved model (file: mymodel_1.pt), in order to not retraining the model.

Unfortunately I can't figure out how to do this (sorry I'm not very experienced).
Is there a command to load a saved model and to use it? 
Do I have to use Torch (that is very difficult to use for me)?

Ref: https://pytorch.org/tutorials/beginner/saving_loading_models.html 

Or must I have to use the "Checkpoints"?
In this case, for use the code in the manual, the import for function ModelCheckpoint and TensorBoardLogger are these?

from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import TensorBoardLogger

Thanks all very much.

**Comment by ethanwhite** [comment]
We provide a function for loading your own models:  `main.deepforest.load_from_checkpoint()`. Here's a very short example of it being used

```python
from deepforest import main
from deepforest import get_data

img_path = get_data("OSBS_029.png")

reloaded_model = main.deepforest.load_from_checkpoint("./mymodel_1.pt")
predict_from_reloaded_model = reloaded_model.predict_image(path = img_path)
```

Relevant docs are here: https://deepforest.readthedocs.io/en/latest/getting_started.html#saving-and-loading-models

Let me know if that takes care of things for you.

**Comment by Caio-Giulio-Cesare** [comment]
> We provide a function for loading your own models: `main.deepforest.load_from_checkpoint()`. Here's a very short example of it being used
> 
> ```python
> from deepforest import main
> from deepforest import get_data
> 
> img_path = get_data("OSBS_029.png")
> 
> reloaded_model = main.deepforest.load_from_checkpoint("./mymodel_1.pt")
> predict_from_reloaded_model = reloaded_model.predict_image(path = img_path)
> ```
> 
> Relevant docs are here: https://deepforest.readthedocs.io/en/latest/getting_started.html#saving-and-loading-models
> 
> Let me know if that takes care of things for you.

Thank you so very much!
Always very kind, I hope one day to have the opportunity to reciprocate your support and kindness.
Thanks again.

**Comment by ethanwhite** [comment]
You're welcome!
