### ISSUE TITLE
Easier yapf checking

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#497]
We currently only do style checking on Azure, which is slower than GH Actions and requires several extra clicks to see what is going on. Ideally we could move this step over to GH Actions and integrate it with our local development process so we spend less time tracking down style issues during PR review.

@henrykironde - is this something we can add to pytest or add a git hook for for local development? Can you try setting up the current test running on Azure on GH Actions?

**Comment by satsin06** [comment]
Will removing this [script](https://github.com/weecology/DeepForest/blob/822d72da4d6321b44687dbcd0cb9adb8c80ef2da/azure-pipelines.yml#L32-L36) from azure-pipelines.yml file and adding 
`- name: Lint with flake8
      run: |
        yapf -d --recursive deepforest/ --style=.style.yapf 2>&1
`
to .github/workflows/Conda-app.yml file fix this issue?

**Comment by henrykironde** [comment]
yes

**Comment by satsin06** [comment]
Ok, I am creating a PR

**Comment by satsin06** [comment]
I have created PR #503, please review it.
