### ISSUE TITLE
Check nms in keras-retinanet

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#5]
It looks like the upstream fork of retinanet isn't implementing non-max suppression for overlapping boxes in the same way. I remember there being chatter about this in the retinanet slack channel. Need to look at my old fork to see what I did. 

@marconiS heads up here, this will look ugly until fixed. Too many overlapping boxes. 
![Figure_1](https://user-images.githubusercontent.com/1208492/66178863-a6e45c80-e61b-11e9-9cba-252f05f02b43.png)

**Comment by MarconiS** [comment]
this was solved using `nms_threshold` in your deepForest, right? In that case let me dive in your repo and try to integrate non maximal suppression in my implementation.

**Comment by MarconiS** [comment]
for what I have seen in your old repo, the main thing that you changed was the noms threshold, from 0.5 (default) to 0.1?

**Comment by bw4sz** [comment]
done. 
![image](https://user-images.githubusercontent.com/1208492/66670831-8b76e400-ec0f-11e9-9081-447fdd8d61a4.png)

**Comment by MarconiS** [comment]
was it just the nms_threshold or anything else?
