### ISSUE TITLE
Make a Contributing.md

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#513]
Perhaps this is superficial,

but I want this badge score to be stronger:

https://snyk.io/advisor/python/deepforest

I think we just need to copy:
https://deepforest.readthedocs.io/en/latest/developer.html

<img width="810" alt="image" src="https://github.com/weecology/DeepForest/assets/1208492/63bf8e75-52a9-4ab3-8137-96f2935e2a16">

is this silly?

**Comment by ethanwhite** [comment]
I think adding a `CONTRIBUTING.md` file is a good idea and in general I think the things that snyk is focusing on are all good things to do that will generally improve our software/docs.

**Comment by bw4sz** [comment]
This needs to be copied to the repo https://github.com/weecology/DeepForest/blob/main/docs/developer.rst
