### ISSUE TITLE
Training stopped after 1 epoch

### ISSUE THREAD

**Issue by yby026** [weecology/DeepForest#535]
Hi there, I'm using DeepForest on a dense forest imagery starting with tree crown detection, and having a trouble I'm not sure how to fix. I'm new on this so this is probably because something I've done wrong, but any suggestion could be extremely helpful.

**Describe the bug**
While I tried to use the pretrained model to train on my own dataset, the training can only run one epoch. I have changed the value of `m.config["epochs"]` several times but all tries stopped at the first epoch. 

**Here is the code I'm using:**
```
m = main.deepforest()
m.use_release()

m.config["workers"] = 2
m.config['gpus'] = '-1'
m.config["epochs"] = 200
m.config["save-snapshot"] = False
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)

m.create_trainer()

m.trainer.fit(m)
```
It always having the same message: 
INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=1` reached.

**And here's the screenshot after running:**
![image](https://github.com/weecology/DeepForest/assets/145319199/eed5573a-11d2-4cb5-b5af-9aa2e7570f11)

**Environment:**
Google Colab, with package version of DeepForest 1.2.7

**Comment by Caio-Giulio-Cesare** [comment]
Hi, I've been using DeepForest for a while now.

I had the same problem as you, try setting from code

m.config["train"]["epochs"] = 200

Or, alternatively, set the value directly in the deepforest_config.yml file

Let me know.

Bye...CIAO

**Comment by bw4sz** [comment]
Yup that's right, check out the config definition here. You are making up a new key 'epochs', but the trainer is looking at 'train' then 'epochs'. 

https://deepforest.readthedocs.io/en/latest/ConfigurationFile.html

More broadly, happy to hear all feedback about how to make the new user experience easier. Anything we could have done better?

**Comment by bw4sz** [comment]
Closing, feel free to open, but this should be solved. Happy to answer more in the issues.
