### ISSUE TITLE
Update the environment.yml for GPU env

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#543]
The GPU environment needs to install pytorch from the pytorch channel, see 

https://github.com/weecology/EvergladesTools/blob/a2e2a5f5b57ae46df05a88aae5b221745d2eae50/Zooniverse/environment.yml#L8

**Comment by Om-Doiphode** [comment]
I have issued a pull request, please review it. Thanks!

**Comment by ethanwhite** [comment]
Fixed in 7b045aeff3d5c2a3c34ccb210db6c6395e79a20e. Thanks again @Om-Doiphode!
