### ISSUE TITLE
module 'deepforest.utilities' has no attribute 'boxes_to_shapefile'

### ISSUE THREAD

**Issue by juangueher** [weecology/DeepForest#555]
Dear Benjamin

The package is working well even for a UAV-RGB large image with the function model.predict_tile. However, I have problem to export boxes to shapefile becouse module utilities it is not working for me

from deepforest import main
from deepforest import get_data
from deepforest import utilities
import os
import rasterio as rio
import numpy as  np

raster_path = get_data("/content/drive/MyDrive/Colab Notebooks/133_ortofoto_rgb_recorte_deepforest_area_grande_RGB2.png")
r = rio.open(raster_path)
df = r.read()
rolled_df = np.rollaxis(df, 0,3)

m = main.deepforest()
m.use_release()

boxes = m.predict_tile(image=rolled_df, patch_size=1500)

shp = utilities.boxes_to_shapefile(boxes, rgb=raster_path, projected=True)

shp.to_file("/content/drive/MyDrive/Colab Notebooks/shp/133_ortofoto_rgb_recorte_deepforest_area_grande_RGB_boxes.shp")

AttributeError                            Traceback (most recent call last)
[<ipython-input-11-667e8c2c60f2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 shp = utilities.boxes_to_shapefile(boxes, root_dir="/content/drive/MyDrive/Colab Notebooks/shp", projected=True)

AttributeError: module 'deepforest.utilities' has no attribute 'boxes_to_shapefile'

Thank you in advance

**Comment by bw4sz** [comment]
Thanks, can you check the package version? I'm guessing you are out of date?

```
(DeepForest) benweinstein@Bens-MacBook-Pro DeepForest % python
Python 3.9.6 (default, Jul 30 2021, 09:31:09)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import __version__
>>> print(__version__)
1.2.7
>>> from deepforest.utilities import boxes_to_shapefile
>>>
>>>
>>> boxes_to_shapefile
<function boxes_to_shapefile at 0x7f7caaaa5af0>
```

try 

``` 
pip install DeepForest --upgrade
```

**Comment by ethanwhite** [comment]
Closing since no response in several months. @juangueher - feel free to reopen if you are still having issues.
