### ISSUE TITLE
NameError: name 'a' is not defined 

### ISSUE THREAD

**Issue by aguirrejuan** [weecology/DeepForest#558]
Hi, 

I have looked at the callback code,  and in nowhere the variable `a` is found,  maybe is `results`  instead?

https://github.com/weecology/DeepForest/blob/8144face5ed34509e1872aa482408437091da120/deepforest/callbacks.py#L104

Thanks.

**Comment by ethanwhite** [comment]
Hi @aguirrejuan!  Thanks for the issue. Can you provide a reproducible example showing this error being generated so that we can look into it more?

**Comment by bw4sz** [comment]
Yes, I see this, I find it strange that this crept in, I'm looking in git logs when this happened, it must have been very recently (last week?). The bigger question is how none of our tests caught it. Pushing a quick fix now, but then we need to open an issue on why the tests didn't cover this. Nothing obvious.
