### ISSUE TITLE
Multi class detection

### ISSUE THREAD

**Issue by jyo94** [weecology/DeepForest#571]
Thank you for your response. Apologise for not clearly specifying my problem. I will try to rephrase it,

I want to built a multi class detection model using deepforest. I have 2 labels ( "cassava" and "weed"). I didn't get a proper idea (after reading the documentation) on how to change the config, to make it a multi class model. So, I made 2 models, one for detecting cassava and the other for weed. 
In both the models, I changed the label to tree as shown below and removed the other label,
```
crop_dir = os.path.join(os.getcwd(),f"train_data_folder/train_data_folder_{image_name.split('.')[0]}")
train_file= os.path.join(crop_dir,"train.csv")
train_df['label'] = train_df['label'].replace({'Weed':'Tree'})
train_df_mod = train_df[train_df['label'] != 'Cassava']
train_df_mod.to_csv(os.path.join(crop_dir,"train_mod_weed.csv"))
```
And used this file in the config settings,
<img width="433" alt="image" src="https://github.com/weecology/DeepForest/assets/146371475/0b17e3cc-c78b-4719-8454-2de220574903">

And have saved this model, 
`m.trainer.save_checkpoint("{}/checkpoint_weed.pl".format(tmpdir))`

Next loaded the saved model using "load_from_checkpoint" function and predicted for a new image using "predict_tile" function. The result I'm getting is the below screenshot,

![sample_output_1 (1)](https://github.com/weecology/DeepForest/assets/146371475/3f8785f8-5d47-4910-8611-48cec0faf7e3)

Now the issues are,
1. All objects are detected as Tree
2. All objects (cassava and weed) are detected though I loaded cassava checkpoint model

I have no idea on how to train for a custom data. And also how to approach a multi class problem.

Hope I have cleared in explaining my issue this time.

**Comment by jyo94** [comment]
Here is the link to the single class detection, ([colab link](https://colab.research.google.com/drive/1XdjvYzqH1aTWPU345J4CB8ZGvn4ozExy?usp=sharing))

**Comment by jyo94** [comment]
@bw4sz @ethanwhite @bendmorris @easz @fluby 
Requesting the developers to help in this matter

**Comment by ethanwhite** [comment]
A couple of general suggestions for helping us help you as quickly as  possible:

1. Each issue should be limited to one topic. So, your question about the two colored boxes in the single class detection should be in a separate issue from your questions about multi-class detection.
2. Try to figure out precisely which command is causing the error (or unexpected behavior) you are seeing and focus your issue just on that command and the code that gets you to that point. Ideally this involves provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that runs using our provided example data, but anything you can do to minimize the amount of code we have to look at to understand your issue will help us get back to your faster.
3. Spam tagging users doesn't help anything. Two of the people you tagged in this issue have nothing to do with this project.

**Comment by ethanwhite** [comment]
With respect to your issues with multi-species modeling:

1. Can you confirm that the [example in the docs](https://deepforest.readthedocs.io/en/latest/multi_species.html) works for you.
2. Can you create a version of your code that matches that but swaps in your csv file and root directory, then show us that code with the resulting error.

**Comment by jyo94** [comment]
> With respect to your issues with multi-species modeling:
> 
> 1. Can you confirm that the [example in the docs](https://deepforest.readthedocs.io/en/latest/multi_species.html) works for you.
> 2. Can you create a version of your code that matches that but swaps in your csv file and root directory, then show us that code with the resulting error.

When I tried to replicate as given in the docs. I'm getting an error that **"AttributeError: 'deepforest' object has no attribute 'num_classes'"**

**Comment by bw4sz** [comment]
Okay, i'm looking into this today. Thanks for your patience. Let's fix the documentation and get the config args structured correctly. num_classses is now

https://github.com/weecology/DeepForest/blob/ff63abbe960c2f74f98f4143b49d0d2417a3ce96/deepforest_config.yml#L12

```
config["num_classes"]
```

**Comment by ethanwhite** [comment]
Thanks for your patience @jyo94. We've now fixed the problem that was causing the error you ran into #580.

If you have git installed on your computer can you install the current development version using the following command:

```
pip install git+https://git@github.com/weecology/deepforest.git
```

And then try to run the code in the [newly updated example in the docs](https://deepforest.readthedocs.io/en/latest/multi_species.html)?

**Comment by ethanwhite** [comment]
@jyo94 - we have now released the fixed version so you can just update to the newest version using `pip install deepforest --upgrade`

**Comment by jyo94** [comment]
@ethanwhite Thanks for the quick response. The multi-class detection issue is now resolved after updating to the new version and following the updated documentation.

**Comment by ethanwhite** [comment]
Your welcome @jyo94! Thanks for reporting the issue and glad it's sorted out! Definitely keep letting us know if you have questions or problems as your work proceeds!
