### ISSUE TITLE
split raster without annotation file

### ISSUE THREAD

**Issue by jyo94** [weecology/DeepForest#576]
I found while training splitting the image into smaller tiles and predicting gives good prediction results. Now for a new image which doesn't have respective annotation file, is it possible to split_raster function. If not, what is the function for this senerio?

**Comment by ethanwhite** [comment]
We typically handle this process using `predict_tile()`, which doesn't require an annotations file, does the raster splitting for you, and returns everything reassembled https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-tile

Is there a reason you need to use `split_raster()` directly?

**Comment by ethanwhite** [comment]
Closing for now. @jyo94 - please feel free to reopen if you still have questions/issues accomplishing what you're trying to do.
