### ISSUE TITLE
Reduce retinanet min anchor size?

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#6]
Retinanet config can lower anchor boxes sizes. @MarconiS add any feedback here. I think our results at NIWO may be effected by this.

**Comment by MarconiS** [comment]
my feeling is that it could very well be the case. The problem in hand tuning the parameters, I wonder, could be in generability. Fortunately seems it has been proposed a method to automatically adjust min anchors size (https://github.com/martinzlocha/anchor-optimization/) based on the size of training bounding boxes. I would try to use that and see if (1) affects configuration of anchors in the first place, and (2) if will affect NIWO. The end goal being that we could use that script in determining the anchor size for each NEON site at the fine-tuning step

**Comment by bw4sz** [comment]
I increased the image size to 800 min-side. Again this is a specific to a project and not this repo.
