### ISSUE TITLE
Make sure the docs is clearer about order of searching deepforest_config.yml path

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#613]
It looks first in your current working directory, if it can't find that, it goes to default config.

https://deepforest.readthedocs.io/en/latest/ConfigurationFile.html#config

**Comment by Om-Doiphode** [comment]
I have issued a pull request, please review it. Thanks!

**Comment by ethanwhite** [comment]
Completed in #623. Thanks again @Om-Doiphode!
