### ISSUE TITLE
Wrong path of image file

### ISSUE THREAD

**Issue by Mu-Magdy** [weecology/DeepForest#614]
Hi @henrykironde 

My name is Muhammed Magdy, I want to participate in GSoC this year. I really like the idea " Modernizing Tree Detection with Advanced Object Detection Models ".
I followed the developer guide and while trying to run  'docs\sample.ipynb'

I got the error that the test image is not found

So can you please add the image to the path

**Comment by henrykironde** [comment]
@Mu-Magdy Executing the file as-is in the main section should not result in errors, as it solely incorporates library imports.

**Comment by Mu-Magdy** [comment]
Aha I see now, It is mainly to test the library imports not the prediction.
I was confused because when I uncommented the code it gave me that error.
Sorry for the misunderstanding. 🤦‍♂️

I want to ask a question regarding the GSoC mentors.
What is the way to communicate with the mentors? 
I have some questions regarding the idea I am interested in
