### ISSUE TITLE
 The link to developer guide in the readme file is wrong 

### ISSUE THREAD

**Issue by Mu-Magdy** [weecology/DeepForest#621]
**Describe the bug**

The link to developer guide in the readme file is wrong. 
the current one is : https://deepforest.readthedocs.io/en/latest/developer.html
it should be : https://deepforest.readthedocs.io/en/latest/CONTRIBUTING.html

If you can please merge the PR to change the link

**Comment by ethanwhite** [comment]
Fixed in 65bd653cd9144c7ccbfd6f058fd7f82129c9587d. Thanks for the contribution @Mu-Magdy!
