### ISSUE TITLE
Error: shapefile_to_annotations() got an unexpected keyword argument 'convert_to_boxes'

### ISSUE THREAD

**Issue by JoseFRuiz** [weecology/DeepForest#643]
**Describe the bug**
I am following the instructions to turn a shapefile into a dataframe of bounding box annotations but there is a problem with the parameter "convert_to_boxes"

**To Reproduce**
```
from deepforest.utilities import shapefile_to_annotations
df = shapefile_to_annotations(
    shapefile=os.path.join(os.getcwd(),'..','training_labels','imgname.shp'), 
    rgb=os.path.join(os.getcwd(),'..','training_data','imgname.png'),
    convert_to_boxes=True, buffer_size=0.15
)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[20], line 1
----> 1 df = shapefile_to_annotations(
      2     shapefile=os.path.join(os.getcwd(),'..','training_labels','imgname.shp'), 
      3     rgb=os.path.join(os.getcwd(),'..','training_data','imgname.png'),
      4     convert_to_boxes=True, buffer_size=0.15
      5 )

TypeError: shapefile_to_annotations() got an unexpected keyword argument 'convert_to_boxes'
```
**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version and environment : Python 3.11.2, Conda

**Comment by JoseFRuiz** [comment]
I just realized that instead of "convert_to_boxes=True", I have to use "geometry_type='point'", but I got a new error:

File ~\anaconda3\envs\myenv\Lib\site-packages\deepforest\utilities.py:299, in shapefile_to_annotations(shapefile, rgb, buffer_size, geometry_type, savedir)
    296     raster_crs = src.crs
    298 # Check matching the crs
--> 299 if not gdf.crs.to_string() == raster_crs.to_string():
    300     raise ValueError("The shapefile crs {} does not match the image crs {}".format(
    301         gdf.crs, src.crs))
    303 # Transform project coordinates to image coordinates

AttributeError: 'NoneType' object has no attribute 'to_string'

**Comment by bw4sz** [comment]
Thanks for the issue. Point annotations are still pretty new, i'm not surprised. What's happening here is that we expected everyone with point annotations to have projected data. Your data must not have a CRS. In general, point annotations are not well supported until this PR is merged 

https://github.com/weecology/DeepForest/pull/590

which won't be for a couple months. 

I can fix this issue quickly, but in general we suggest you annotate boxes, not points until this area is more mature.

**Comment by JoseFRuiz** [comment]
Got it. Thanks!
