### ISSUE TITLE
Tree species classification

### ISSUE THREAD

**Issue by TSAI-ChengEn** [weecology/DeepForest#662]
If I divide the tree data in the dataset into four categories, can I distinguish different types of trees by changing the 'Tree' field in the label to 'cluster1', 'cluster2', etc., after training the model? Or are there any other methods to distinguish different categories of trees?        

Thank you for answering my question.

**Comment by s44002** [comment]
i have my sincere doubts that that might work, also, from where are you getting the satellite data necessary??

**Comment by ethanwhite** [comment]
It is possible to use the DeepForest backbone to train multi-species models. Here's the relevant documentation:
https://deepforest.readthedocs.io/en/latest/multi_species.html

How well this will work depends primarily on how distinguishable different types of trees are in the imagery (if you can tell the difference the model can probably learn it, but if you can't then it likely can't) and on how much hand annotated training data you have.

**Comment by bw4sz** [comment]
Please use discussions, issues are not the right place for this conversation.
