### ISSUE TITLE
Rethink warning about 'no validation file' when loading or creating a model with default deepforecast_config.yml

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#664]
The most basic thing we do triggers a warning that is confusing to users:

```python
>>> from deepforest import main
>>> model = main.deepforest()
Reading config file: /home/ethan/miniconda3/envs/DeepForest/lib/python3.11/site-packages/deepforest/data/deepforest_config.yml
No validation file provided. Turning off validation loop
...
```

We've gotten a number of questions (#557, #655, #653), about this warning and it is particularly confusing if users add a validation file in the code and then create a trainer, since they are seeing an error that implies that this didn't work, but it's actually occurring before the validation file is defined and the trainer created.

**Comment by bw4sz** [comment]
Yes, in general I think it actually could be silent without a problem.
