### ISSUE TITLE
View train loss

### ISSUE THREAD

**Issue by TSAI-ChengEn** [weecology/DeepForest#678]
I used TensorBoard and saw val_classification and val_bbox_regression.

How should I view the train loss after the model training is completed?

Thank you for taking the time to answer my question.

**Comment by TSAI-ChengEn** [comment]
I am wondering whether this is an issue on my end or are there any adjustments I need to make?
I hope you can help me answer my question, thank you.

**Comment by bw4sz** [comment]
Please use issues for bugs or requests for new features. For general discussion, please create a discussion and outline a much fuller example and question. Not enough information here to help.
