### ISSUE TITLE
File input reader types

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#7]
Current status is to use the csv generator, so the files need to be read directly from PIL. @marconiS any resolution to what you did? Moving forward I will not be using those old weights from DeepLidar repo.

Long term i think I want atleast a numpy reader, so that images can be cut from tiles and saved into numpy arrays. To reason to waste time as .jpgs

- [ ] numpy reader
General idea would be to replace the csv -generator with a numpy.save and numpy.load

https://stackoverflow.com/questions/30329726/fastest-save-and-load-options-for-a-numpy-array

- [x] tfrecords. Eventually we want to pipe the data straight into tensorflow and avoid all the python overhead 
https://www.dlology.com/blog/how-to-leverage-tensorflows-tfrecord-to-train-keras-model/

**Comment by MarconiS** [comment]
Sure, so the keras-retinanet CSVgenerator calls the function `read_image_bgr(path)` in `image.py`. There, you can replace `return image[:, :, ::-1].copy()` with 

<img width="557" alt="Screen Shot 2019-10-11 at 1 34 38 PM" src="https://user-images.githubusercontent.com/11638797/66672255-e28ab200-ec2b-11e9-895f-e43b39543055.png">

**Comment by bw4sz** [comment]
tfrecords complete in dev branch, needs to be merged to master.
