### ISSUE TITLE
Check unused dependencies

### ISSUE THREAD

**Issue by Mu-Magdy** [weecology/DeepForest#723]
Compare the requirements file to check if we are installing unneeded requirements
Tried to use [pipreqs](https://pypi.org/project/pipreqs/) to check for requirements, but it only generates the requirements that are imported in the file so it misses some system packages 
I will make here like a thread checking if we need this module or not

**Comment by ethanwhite** [comment]
@Mu-Magdy - was this closed by #725 or is there still more work to be done. If #725 took care of it you can go ahead and close. Thanks!

**Comment by Mu-Magdy** [comment]
Hi @ethanwhite 

I think that I can make a new pr and try to delete some modules that i can't see directly in code then make a commit to check if the tests fails then that module is used. if tests pass that means it is not used.

Do you think this is the best approach or there is a better one?

ps: I tried python libraries that make automatic requirements.txt file like ( pipreqs ) but it mainly goes through all .py files and write imported libraries in requirements.txt file it doesn't check for docs build or other files

**Comment by Mu-Magdy** [comment]
As mentioned on slack all other libraries are used for documentation. That closes this issue
