### ISSUE TITLE
Can't convert prediction results to supervision format

### ISSUE THREAD

**Issue by camappel** [weecology/DeepForest#745]
**Describe the bug**
The [Visualisation](https://github.com/weecology/DeepForest/blob/main/docs/visualizations.md) page is out of date, I believe: convert_to_sv_format no longer exists in the deepforest.visualize module.

**To Reproduce**
```
from deepforest.visualize import convert_to_sv_format
import deepforest.visualize as visualize
print(dir(visualize))
```
Returns
```
['Image', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'cv2', 'format_boxes', 'label_to_color', 'matplotlib', 'np', 'os', 'pd', 'plot_points', 'plot_prediction_and_targets', 'plot_prediction_dataframe', 'plot_predictions', 'ptypes', 'random', 'view_dataset', 'warnings']
---------------------------------------------------------------------------
ImportError 
```

**Environment (please complete the following information):**
 - OS: macOS Ventura
 - Python version and environment : 3.10.12

**Comment by camappel** [comment]
I see this function is mentioned in #697 and is in https://github.com/weecology/DeepForest/blob/main/deepforest/visualize.py so I'm not sure why the function can't be found

**Comment by ethanwhite** [comment]
Sorry for the confusion @camappel - that function is new since the last release and the docs are currently being built for the `main` branch.

Assuming you have git installed you can install the current development version with that function using:

```sh
pip install git+https://github.com/weecology/deepforest
```

I'll open an issue to do some work on the docs to display the current release by default.

If this clears things up feel free to close.

**Comment by camappel** [comment]
Thanks for the response! The following code worked
```
pip uninstall deepforest -y
pip install git+https://github.com/weecology/deepforest

import deepforest.visualize as dv
dv
```
Returned
```
<module 'deepforest.visualize' from '/Users/cam/Library/CloudStorage/GoogleDrive-camdappel@gmail.com/My Drive/colab/DeepForest_Project/deepforest-env/lib/python3.9/site-packages/deepforest/visualize.py'>
```

**Comment by ethanwhite** [comment]
Glad that took care of it and thanks for reporting! We'll get that aspect of the docs cleaned up to avoid this very confusing kind of experience in the future.
