### ISSUE TITLE
Livestock model 

### ISSUE THREAD

**Issue by camappel** [weecology/DeepForest#765]
**Describe the bug**,
I'm currently trying to fine-tune the livestock detection model using a publicly available [dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/N7GJYU). While the livestock detection model is listed on HuggingFace, I can't find the relevant function anywhere in the DeepForest. Has this model been added yet? Many thanks!

**To Reproduce**
```
>>> model.use_livestock_release()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cam/miniconda3/envs/deepforest/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'deepforest' object has no attribute 'use_livestock_release'
```

**Environment (please complete the following information):**
 - OS: Mac
 - Python version and environment :  3.10

**Screenshots and Context**
<img width="923" alt="Screenshot 2024-09-03 at 20 18 19" src="https://github.com/user-attachments/assets/bc4fb257-aa50-4020-b0d6-c7bee68cd0c1">

**User Story**
The project goals are described [here](https://github.com/alan-turing-institute/environmental-ds-book/issues/257)

**Comment by camappel** [comment]
I notice the .pt file was available in a previous (commit)[https://huggingface.co/weecology/deepforest-livestock/commit/9d1264a4de04b4651f73d7453aca93dd1640f2ae] - is it still OK to use the model?

**Comment by ethanwhite** [comment]
We're in the process of setting  up expanded model support in deepforest. Until #762 is merged it won't be possible to use new models. Once it's merged then it should work installing from the `main` branch of this repo and we'll hopefully ship a new release not long after that.

@bw4sz can update you on the status of the model itself. Given the design in #762 I suspect we pulled the .pt file because we've switching over to using .safetensors for distribution on huggingface.

**Comment by bw4sz** [comment]
I believe the model is trained and can be used. We are waiting on those pull requests to be merged. The deleted file can still be grabbed from history.

https://huggingface.co/weecology/deepforest-livestock/blob/ee1afe6889f0f8bfe8abfa25d9d4894e2a496068/livestock.pt

```
from deepforest import main
from deepforest import visualize
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np

image_path = "/Users/benweinstein/Dropbox/Weecology/Livestock/SheepCounter.v15-sheep-counter-working.retinanet/valid/DJI_0005_0074_jpg.rf.99c7c3ce9059fffb0ad408710759fbc7.jpg"
image = np.array(Image.open(image_path))
m = main.deepforest.load_from_checkpoint("/Users/benweinstein/Downloads/livestock.pt")
boxes = m.predict_image(image=image)
boxes = boxes[boxes["score"] > 0.3]
fig = visualize.plot_predictions(image=image, df=boxes)
plt.imshow(fig)
plt.show()
```
<img width="647" alt="image" src="https://github.com/user-attachments/assets/193ca40d-1c7c-46e8-82b9-4314aa451735">

Not perfect, but a start. I strongly underline this is a brand new model, and in need of data. If you find it useful, please consider contributing training data to make it better for others. This is the only way we can make progress.

**Comment by camappel** [comment]
Thanks for getting back to me - I was able to download the weights and load from checkpoint as described.

I have a massive dataset of labelled cows, so assuming I train the model properly I should be to improve the model's accuracy - I'm happy to then share the training data and updated weights on huggingface.

**Comment by ethanwhite** [comment]
Thanks @camappel. FYI the weights are now back up as a safetensor file https://huggingface.co/weecology/deepforest-livestock/discussions/3

**Comment by camappel** [comment]
Brilliant, thanks! I'm aiming to complete the project by then end of this week
