### ISSUE TITLE
mismatch between documentation and DeepForest version 1.4.0

### ISSUE THREAD

**Issue by robinsandfort** [weecology/DeepForest#776]
Hi,
I´m trying to follow the 
https://deepforest.readthedocs.io/en/latest
and often find functions introduced with DeepForest 1.4.0.
For example here:
https://deepforest.readthedocs.io/en/latest/getting_started/Reading_and_Writing.html

Is this version already released or where can I find it?

Greetings,
Robin

**Comment by robinsandfort** [comment]
Hi Ethan,
thanks for the info and the great work! The install of 1.4.0 does not work
`pip install git+https://github.com/weecology/DeepForest.git`
still installs: deepforest 1.3.3 
Any idea?
Greetings,
Robin

**Comment by ethanwhite** [comment]
It is installing the current dev version with all of the functionality described in the `latest` docs. Since we haven't released yet we haven't updated the version number. Does that make sense?
