### ISSUE TITLE
Update Python requirements to 3.8, 3.9, 3.10, 3.11, 3.12

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#812]

**Comment by Abhishek-kumar0503** [comment]
To update Python requirements to support versions 3.8 through 3.12, i can modify in  project's file name `pyproject.toml` .
Would you give permission to recorrect it.

**Comment by henrykironde** [comment]
Thanks @Abhishek-kumar0503 for the recommendation. We have it added in #828. Feel free to test that PR and update where you feel necessary.

**Comment by ethanwhite** [comment]
Fixed in #832
