### ISSUE TITLE
Expanding DeepForest Authorship – Request for Permission

### ISSUE THREAD

**Issue by henrykironde** [weecology/DeepForest#821]
Hi @Mu-Magdy, @Om-Doiphode, @dingyif,

DeepForest is built on the collective effort of many contributors, and we are immensely grateful for every contribution, no matter how big or small. As part of our ongoing initiative to recognize contributions, we are gradually expanding the authorship list. With each major release, we will add a few individuals whose work has significantly shaped the project during that period.

For this release, we’d like to acknowledge your valuable efforts by adding you as official authors. To move forward, we need your permission to include your name in the authorship list. Of course, please feel free to decline if you prefer.

To proceed, we’ll also need your ORCID. If you don’t already have one, you can create it at https://orcid.org/. ORCID ensures consistent attribution of your contributions across your entire academic and professional career.
Thank you again to the entire DeepForest community—we couldn’t do this without each and every one of you!

Please comment with these details 

```Json 
      {
        "affiliation": "University of Florida",
        "name": "Henry Senyondo",
        "orcid": "0000-0001-7105-5808",
        "email": " email@email.com",
      },
```

**Comment by Mu-Magdy** [comment]
Hi @henrykironde 
hope you are fine,
This is an honor to be recognized as a contributor in this great project by talented people like you,
{
        "affiliation": "University of Florida",
        "name": "Muhammed Magdy",
        "orcid": "0009-0009-6167-7246",
        "email": " muhammedmagdy1015@gmail.com",
      },

**Comment by Om-Doiphode** [comment]
Hi @henrykironde, following are the details:
```
      {
        "affiliation": "University of Florida",
        "name": "Om Doiphode",
        "orcid": "0009-0007-2592-7370",
        "email": "omdoiphode161@gmail.com",
      }
```

**Comment by dingyif** [comment]
Hi @henrykironde ,
Happy Holiday! 

{
        "affiliation": "Columbia University",
        "name": "Dingyi Fang",
        "orcid": "0009-0006-8532-5024",
        "email": "imfangdingyi@gmail.com",
      }
