### ISSUE TITLE
Training  problem Got processor for bboxes, but no transform to process it.

### ISSUE THREAD

**Issue by robinsandfort** [weecology/DeepForest#848]
Hi, 
trying to replicate your examples (bird nests) and my own data
training always stops at the same point:

**Environment (please complete the following information):**
 - OS: Mac and windows
 - Python version and environment : 3.13.1 conda env

Using your Tutorial for training a nest detection model

`# Start the training

start_time = time.time()

m.trainer.fit(m)`

I get:

UserWarning: Consider setting `persistent_workers=True` in 'train_dataloader' to speed up the dataloader worker initialization.
/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 1.4.22 (you have 1.4.21). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
UserWarning: Got processor for bboxes, but no transform to process it.
UserWarning: Consider setting `persistent_workers=True` in 'val_dataloader' to speed up the dataloader worker initialization.

and then:

"name": "KeyError",
	"message": "Caught KeyError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/torch/utils/data/_utils/worker.py\", line 351, in _worker_loop\n    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n            ~~~~~~~~~~~~^^^^^\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/deepforest/dataset.py\", line 110, in __getitem__\n    targets[\"labels\"] = image_annotations.label.apply(\n                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        lambda x: self.label_dict[x]).values.astype(np.int64)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/pandas/core/series.py\", line 4924, in apply\n    ).apply()\n      ~~~~~^^\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/pandas/core/apply.py\", line 1427, in apply\n    return self.apply_standard()\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/pandas/core/apply.py\", line 1507, in apply_standard\n    mapped = obj._map_values(\n        mapper=curried, na_action=action, convert=self.convert_dtype\n    )\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/pandas/core/base.py\", line 921, in _map_values\n    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/pandas/core/algorithms.py\", line 1743, in map_array\n    return lib.map_infer(values, mapper, convert=convert)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"lib.pyx\", line 2972, in pandas._libs.lib.map_infer\n  File \"/opt/anaconda3/envs/deepforest/lib/python3.13/site-packages/deepforest/dataset.py\", line 111, in <lambda>\n    lambda x: self.label_dict[x]).values.astype(np.int64)\n              ~~~~~~~~~~~~~~~^^^\nKeyError: 'Nest'\n",

**Comment by henrykironde** [comment]
@robinsandfort Thank you for reporting the issue! Could you clarify which example you're trying to replicate? 

Please verify that the `label` column in your dataset contains the correct labels and matches those in the `label_dict`. Let us know if that works.

**Comment by robinsandfort** [comment]
@henrykironde Hi Henry,
for example this one:
https://deepforest.readthedocs.io/en/v1.4.1/user_guide/examples/nest_detection.html

I somehow think that 

`##Set parameters for the training run

#Define the pre-trained model
model = main.deepforest()

model.config['gpus'] = '-1' #move to GPU and use all the GPU resources

#model.config["save-snapshot"] = False
#model.config["train"]["fast_dev_run"] = True

#The annotation table
model.config["train"]["csv_file"] = training_file
#The directory where the training imagery is located
model.config["train"]["root_dir"] = os.path.dirname(training_file)

model.config["score_thresh"] = 0.4
model.config["train"]['epochs'] = 4

model.config["validation"]["csv_file"] = validation_file
model.config["validation"]["root_dir"] = os.path.dirname(validation_file)


model.create_trainer()
`

Is not correctly created. Where are this settings saved?
deepforest_config.yml is not changed:
args?


Greetings,
Robin

**Comment by robinsandfort** [comment]
Maybe no dataloader is defined?

![training](https://github.com/user-attachments/assets/0059be6d-9db2-4592-a436-f1168a058841)

**Comment by robinsandfort** [comment]
> @robinsandfort Thank you for reporting the issue! Could you clarify which example you're trying to replicate?
> 
> Please verify that the `label` column in your dataset contains the correct labels and matches those in the `label_dict`. Let us know if that works.

Hi Henry,
yes. I use the nest exampel files with the `label` Nest and  
m = main.deepforest(label_dict={"Nest": 0})

**Comment by robinsandfort** [comment]
Got it running. Most likely it was a mismatch between label_dict and the label column.
Thanks for your hind!
