### ISSUE TITLE
 There is no config at, yields deepforest_config.yml

### ISSUE THREAD

**Issue by prasannarajezzzy** [weecology/DeepForest#88]
There is no config at, yields deepforest_config.yml

**Comment by bw4sz** [comment]
sorry, I didn't follow this issue. Inside of every deepforest model is a default config file.

```
from deepforest import deepforest
Using TensorFlow backend.
model = deepforest.deepforest()
Reading config file: /Users/ben/miniconda3/envs/test/lib/python3.7/site-packages/deepforest/data/deepforest_config.yml
A blank deepforest object created. To perform prediction, either train or load an existing model.
model.config
{'batch_size': 1, 'weights': 'None', 'backbone': 'resnet50', 'image-min-side': 800, 'multi-gpu': 1, 'epochs': 1, 'validation_annotations': 'None', 'freeze_layers': 0, 'freeze_resnet': False, 'score_threshold': 0.05, 'multiprocessing': False, 'workers': 1, 'max_queue_size': 10, 'random_transform': False, 'save-snapshot': False, 'save_path': 'snapshots/', 'snapshot_path': 'snapshots/'}
```

**Comment by bw4sz** [comment]
Closing due to insufficient information.

**Comment by L-u-d-0-v-i-c** [comment]
I tried to load deepforest on Google Colab and got the same error:

`FileNotFoundError: There is no config at /usr/local/lib/python3.6/dist-packages/deepforest/data/deepforest_config.yml, yields module 'yaml' has no attribute 'FullLoader'`

**Comment by bw4sz** [comment]
Not a deepforest error I believe, the pyyaml on colab is old. and however you installed didn't force update.

```
https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader
```

**Comment by bw4sz** [comment]
Could you print the pyyaml version and I can pin it if I really must. Only a big deal for pre-installed environments.

**Comment by L-u-d-0-v-i-c** [comment]
It works by installing a newer version. The old one is the 3.13 (5.3.1 for the up-to-date version).

Thanks!

**Comment by bw4sz** [comment]
Great. Pinned >5.1.0, pushed to pypi and conda in the next hour.
