### ISSUE TITLE
Where is predict generator in docs?

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#90]

**Comment by bw4sz** [comment]
sphinx-api doc is not generating all the files!

running 
```
cd /Users/ben/Documents/DeepForest/docs
(DeepForest) MacBook-Pro:docs ben$ sphinx-apidoc -o source/ ../
```
Creates many nice looking html files for SOME but not ALL .py files.
```
(DeepForest) MacBook-Pro:docs ben$ ls source/
deepforest.data.rst			keras_retinanet.bin.rst			keras_retinanet.models.rst		keras_retinanet.utils.rst		tests.rst
deepforest.rst				keras_retinanet.callbacks.rst		keras_retinanet.preprocessing.rst	modules.rst
keras_retinanet.backend.rst		keras_retinanet.layers.rst		keras_retinanet.rst			setup.rst
```

```
(DeepForest) MacBook-Pro:docs ben$ ls ../deepforest/
__init__.py		_version.py		deepforest.py		preprocess.py		tfrecords.py
__pycache__		data			predict.py		retinanet_train.py	utilities.py
```

e.g. deepforest.deepforest.rst or deepforest.tfrecords.rst is not created. No errors.

@henrykironde any experience with sphinx? Any ways to get more logs?

**Comment by henrykironde** [comment]
Use -f to update
`sphinx-apidoc -f -o source/ ../`
I have tested it and it seems to work fine.
The tool will create the files based on the directory level module.
In the deepforest.rst, you will find  `deepforest.tfrecords module` and the reset.

Let me know if this is the  solution

**Comment by bw4sz** [comment]
Not quite, I tried that as well (deleting all the source and regenerating). There are no functions documented, for example in the deepforest.tfrecords class

https://deepforest.readthedocs.io/en/latest/source/deepforest.html#deepforest-tfrecords-module

even though there are functions with docstrings

https://github.com/weecology/DeepForest/blob/c52bf422978d06a578b73924d93f481065b8e046/deepforest/tfrecords.py#L64
